### ISSUE TITLE
LineHeight,  LineSpacing,  Ascending and Descending, GlyphBounds

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#117]
![image](https://user-images.githubusercontent.com/19922066/40539715-3be4ee86-6048-11e8-8eaa-f90e42a2317b.png)

The red box should not cover the area over the red text.

**Comment by prepare** [comment]
**Line height** calculation is correct => It is BTBD ('Baseline-to-Baseline Distance') 
(see more : https://docs.microsoft.com/en-us/typography/opentype/spec/recom#tad)

**But** I place the red box wrong place (too high in Y axis).

so I fixed it in https://github.com/LayoutFarm/Typography/commit/68a163e4a0c460f055a8cf7a0019797ed810c964

----
After offset it down ..., 

![line_height2](https://user-images.githubusercontent.com/7447159/40545376-d15d51b2-6055-11e8-80fe-ee49d06816b7.png)


_pic 1:  (1) BTBD value => use this value for **'line-height'** for multi line text,
(2) **base line** of each line,   (3) ascending, (4)  descending_

**Comment by prepare** [comment]
![line_height](https://user-images.githubusercontent.com/7447159/40545731-0ebb3c62-6057-11e8-8009-289bd546c506.png)

**Comment by prepare** [comment]
(struct) MeasureString  value from LayoutAndMeasureString() is not a sum value on each glyph.
It is used for draw a line of text in general text layout.

**Comment by prepare** [comment]
GlyphBounds
---
![glyph_bounds2](https://user-images.githubusercontent.com/7447159/40576845-267d218c-6127-11e8-9acf-c259395974a2.png)

_pic 2: CFF1 font, latin-modern-math-regular.otf , gdi+ => MeasureTextSpan button shows each GlyphBounds_



![glyph_bounds3](https://user-images.githubusercontent.com/7447159/40576904-cbca2b26-6127-11e8-918c-c49e583b34be.png)

_pic 3: TTF font, tahoma, shows each GlyphBounds_

**Comment by prepare** [comment]
Html5 Canvas2d's textBaseline
Note from https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/textBaseline

![baselines](https://user-images.githubusercontent.com/7447159/72050463-c3b3be80-32f3-11ea-8e70-bd62795e2985.png)

_(img from https://html.spec.whatwg.org/images/baselines.png)_

**Comment by prepare** [comment]
TextBaseline Typography's implementation
---

small red rectangle => (xpos,ypos)

font Asena Math Regular

![baseline_alphabetic](https://user-images.githubusercontent.com/7447159/72068507-c9230000-3317-11ea-874b-39bf51f37aeb.png)
_alphabetic_

---

![baseline_top](https://user-images.githubusercontent.com/7447159/72068509-c9bb9680-3317-11ea-9979-6a2d7d167716.png)

_top_


---
![baseline_bottom](https://user-images.githubusercontent.com/7447159/72068508-c9bb9680-3317-11ea-8826-0bec975c5869.png)

_bottom_

**Comment by prepare** [comment]
![baseline_3](https://user-images.githubusercontent.com/7447159/72069405-b01b4e80-3319-11ea-96df-4b08f6fa5ae4.png)

_3 styles_

**Comment by prepare** [comment]
Reference Imgs:

![alignment_top](https://user-images.githubusercontent.com/7447159/85354716-70e26200-b535-11ea-89ec-3a6fc50582bc.png)

_Source Sans Pro, 20pt, Alignment Top_

**Comment by prepare** [comment]
ธี่ธํ่ธั่วฐูญูกฤู😁

![ref_img](https://user-images.githubusercontent.com/7447159/88776058-af5fe200-d1af-11ea-84a6-fc0afa097029.png)
_Sarabun + TwitterColorEmoji, 72pt_
