### ISSUE TITLE
Glyph.Bounds of variations of a glyph

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#119]
See sample => https://github.com/Happypig375/TypographyGlyphBoundsTest
![image](https://user-images.githubusercontent.com/19922066/40582667-b0adce32-61af-11e8-832b-0385498650a3.png)

**Comment by prepare** [comment]
Thank you for your report.
This was fixed in https://github.com/LayoutFarm/Typography/commit/885ead7e75904e88e8f7de92c441ea1683731f39

---
![issue_119_fixed](https://user-images.githubusercontent.com/7447159/40583056-72a7d956-61b0-11e8-9f0d-5b82b21e2116.png)
