### ISSUE TITLE
Is it just me or are the X and Y values of some of these glyphs not normal?

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#120]
See sample => https://github.com/Happypig375/TypographyGlyphBoundsTest
![image](https://user-images.githubusercontent.com/19922066/40584393-26442c96-61d2-11e8-8b94-27bae39e4198.png)<br/>
_Each glyph placed sequentially, respecting their X values and width. Left to right: radical (abnormally placed under the baseline?), radical.v1 to radical.v4 (they get pushed to the right as the number increases), v6 and v7 of slash, backslash and fraction (v6 is fine but v7 is abnormal)_

**Comment by prepare** [comment]
Here is mine...

![issue_120](https://user-images.githubusercontent.com/7447159/40584640-92f34254-61ce-11e8-906e-40ead78a0523.png)

---

**Comment by Happypig375** [comment]
Yes, the pictures are the same.

**Comment by prepare** [comment]
I need to study more about **'how-to-use each variation'**.

**Comment by prepare** [comment]
@Happypig375 , 

You translate offset to the right ?

So I comment it (red box).

![issue_120_1](https://user-images.githubusercontent.com/7447159/40585140-890ad442-61d7-11e8-8e67-ff834f9d9a59.png)


---

Is this what you want ?

**Comment by Happypig375** [comment]
Note that some of the glyphs are still offset to the right (most notably slash.v7 which separates itself from the cluster to its left).

**Comment by prepare** [comment]
Yes, both slash.v7 and fraction.v7 are pushed to the right.

![issue_120_2](https://user-images.githubusercontent.com/7447159/40585282-14faf76e-61da-11e8-8f4c-2cfc3f28b583.png)

**Comment by prepare** [comment]
Rendered with PixelFarm, latin-modern-math, 20 pts

![issue_120_3](https://user-images.githubusercontent.com/7447159/40585359-7207b284-61db-11e8-90b2-989c54d2aaa3.png)
_(1) radical,  (2) radical.v1 , (3) radical.v2, (4) radical.v3, (5) radical.v4 , (6) slash.v7_

**Comment by prepare** [comment]
They were designed like that?

**Comment by Happypig375** [comment]
Okay, I will do the alignments myself then. Thanks anyways.

**Comment by prepare** [comment]
> Okay, I will do the alignments myself.

What the original code handle these variations ?

**Comment by prepare** [comment]
You may want to look at this too.

(https://github.com/LayoutFarm/Typography/blob/dev/Typography.OpenFont/Tables.AdvancedLayout/MathTable.cs#L1080)


           //MathVariants Table
            //The MathVariants table solves the following problem:
            //given a particular default glyph shape and a certain width or height, 
            //find a variant shape glyph(or construct created by putting several glyph together) 
            //that has the required measurement.
            //This functionality is needed for growing the parentheses to match the height of the expression within,
            //growing the radical sign to match the height of the expression under the radical, 
            //stretching accents like tilde when they are put over several characters, 
            //for stretching arrows, horizontal curly braces, and so forth.

            //The MathVariants table consists of the following fields:


            //  Count and coverage of glyph that can grow in the vertical direction.
            //  Count and coverage of glyphs that can grow in the horizontal direction.
            //  MinConnectorOverlap defines by how much two glyphs need to overlap with each other when used to construct a larger shape. 
            //  Each glyph to be used as a building block in constructing extended shapes will have a straight part at either or both ends.
            //  This connector part is used to connect that glyph to other glyphs in the assembly. 
            //  These connectors need to overlap to compensate for rounding errors and hinting corrections at a lower resolution.
            //  The MinConnectorOverlap value tells how much overlap is necessary for this particular font.

            //  Two arrays of offsets to MathGlyphConstruction tables: 
            //  one array for glyphs that grow in the vertical direction, 
            //  and the other array for glyphs that grow in the horizontal direction.
            //  The arrays must be arranged in coverage order and have specified sizes.

**Comment by Happypig375** [comment]
I managed to solve this by storing the "original bounds" when vertical variants are requested; and translating (-(glyphs[i].Bounds.XMin-glyphs[i].GetOriginalBounds().XMin) * scale, 0) before drawing the glyph.

**Comment by Happypig375** [comment]
@prepare When you fixed #124, I think you also fixed this one. :clap::clap:

**Comment by Happypig375** [comment]
Whoops, I thought it was actually not fixed but then I remembered to update the submodule of the project, so I prematurely deleted that comment. It is indeed fixed now 😆
![image](https://user-images.githubusercontent.com/19922066/41810944-80f8e8c6-7739-11e8-87a5-1a4d2087642c.png)
_(Compare this to the original one, this is so much nicer)_

**Comment by prepare** [comment]
This problem is corrected with https://github.com/LayoutFarm/Typography/issues/124
