### ISSUE TITLE
CloseContour() is not called when running CffEvaluationEngine

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#121]
![image](https://user-images.githubusercontent.com/19922066/40923269-f5b80216-6846-11e8-8397-2fa39c06b801.png)

**Comment by Happypig375** [comment]
I suspect this is the source of https://github.com/verybadcat/CSharpMath/issues/1#issuecomment-394194607.

**Comment by prepare** [comment]
please test with https://github.com/LayoutFarm/Typography/commit/33c6fe1c0f54ebc87eafd5b93432a330b7c56f77

**Comment by Happypig375** [comment]
@prepare See https://github.com/Happypig375/SkiaTest

Gdi+ | SkiaSharp
-|-
![image](https://user-images.githubusercontent.com/19922066/41025155-c12ae230-69a3-11e8-8a37-a372182a9d88.png)|![image](https://user-images.githubusercontent.com/19922066/41025162-c3d711fc-69a3-11e8-9b6f-9c93db9921c3.png)

**Comment by prepare** [comment]
Hello @Happypig375 

for CFF,
please see https://github.com/LayoutFarm/Typography/blob/math_table/Demo/Windows/GdiPlusSample.WinForms/GdiPlus/GlyphTranslatorToGdiPath.cs#L43

You will see that We must check that the contour is closed before begin next move-to operation.

Your code (https://github.com/Happypig375/SkiaTest/blob/master/SkiaTest/Form1.cs#L102)
dose not do this.

---

![glyph_outline](https://user-images.githubusercontent.com/7447159/41030440-8cefa83e-69a8-11e8-970b-3beb4282dc16.png)

_pic 1: my screen, Gdi+ , latin, 𝑑_
