### ISSUE TITLE
Layout Glyphs directly in GlyphLayout?

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#122]
This would allow glyphs from multiple typefaces to be laid out.

**Comment by Happypig375** [comment]
Calculating the layout size of a glyph run, but the glyphs contain both Latin and Chinese (from two different fonts).

**Comment by zwcloud** [comment]
Then we need something like [DWRITE_TEXT_RANGE][1] and [IDWriteTextFormat][2]. This will be a super complex feature, I think.

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/dd368137.aspx
[2]: https://msdn.microsoft.com/en-us/library/windows/desktop/dd316628.aspx

**Comment by Happypig375** [comment]
I will look into this. Hopefully something like `class Typefaces` can come out of this 😛

**Comment by prepare** [comment]
There will be another object to do this work.

a blob of text 
=> a list of text-span (etc, same font,same style, same script) 
=> each span is sent to a 'proper' GlyphLayout.

It is not hard :)

I have done this with the Typography => the result is something like this...

![html002](https://user-images.githubusercontent.com/7447159/41227487-29e2feb2-6d9f-11e8-8a67-a5692dff7e6f.png)

but The classes that handle this work are not stable=>
They are in Typography.TextServices /TextBreak/ TextFlow module

**Comment by prepare** [comment]
Why they are separated into another module?

because of Text breaking algorithm are quite complex, varies in different culture,

etc

1. left-to-right word mixed with right-to-left word.
2. Math word mixed with 'human' word.

**Comment by prepare** [comment]
Why we separate them into a list of text-span (same font,same style, same script) first?

because of GlyphLayout algorithm=>
we need 'context' around a glyph  to do substitution (GSUB) and glyph placement (GPOS) properly.
