### ISSUE TITLE
Why is the wedge placed like this?

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#124]
Text: `345∧54`
![image](https://user-images.githubusercontent.com/19922066/41704698-85558432-7569-11e8-9330-c625dd220b19.png)

**Comment by prepare** [comment]
Thank you for your report. 

It is a CffEvaluationEngine bug.



now fixed: see https://github.com/LayoutFarm/Typography/commit/c7fc404d2abf0f3293ff4e2c0e81fab7f517e624#diff-7fef53107d6766bc849f7b5103582b7bR350


some commands (below, rmove  in this case),
we  need to check if there is 'additional width' argument before it.

---
NOTE4:

(https://github.com/LayoutFarm/Typography/blob/c7fc404d2abf0f3293ff4e2c0e81fab7f517e624/Typography.OpenFont/Tables.CFF/CffEvaluationEngine.cs#L328)

        //[NOTE4]:
        //The first stack - clearing operator, which must be one of...

        //hstem, hstemhm, vstem, vstemhm, cntrmask, 
        //hintmask, hmoveto, vmoveto, rmoveto, or endchar,

        //...
        //takes an additional argument — the width(as
        //described earlier), which may be expressed as zero or one numeric
        //argument


---

![cff_with_additional_width_parameter](https://user-images.githubusercontent.com/7447159/41714107-7245484a-7579-11e8-898b-dab39df72270.png)
