### ISSUE TITLE
Mark structs with only readonly fields as readonly structs

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#154]
Basically `struct A { }` -> `readonly struct A { }`. The compiler can avoid generating defensive copies in some areas.

**Comment by prepare** [comment]
https://devblogs.microsoft.com/premier-developer/the-in-modifier-and-the-readonly-structs-in-c/

**Comment by prepare** [comment]
https://github.com/LayoutFarm/Typography/commit/bfcfab76c015c713e3f7257dc6b688ee2c60c4e3
