### ISSUE TITLE
Implement TTC

### ISSUE THREAD

**Issue by FoggyFinder** [LayoutFarm/Typography#157]
From [ReadMe](https://github.com/LayoutFarm/Typography#concept)

> 1.Loads .ttf, .otf files, with OpenFontReader.

Does it mean there is no support for, let's say, `.ttc` format?

**Comment by Happypig375** [comment]
[`.ttc`s have a `ttcf` table at the start.](https://docs.microsoft.com/en-us/typography/opentype/spec/otff#ttc-header)
Currently the reader expects on `OS/2` table at the start.
https://github.com/LayoutFarm/Typography/blob/a48c5d5c190bdfb347e46a222596c757271d0d3b/Typography.OpenFont/OpenFontReader.cs#L92-L98
So yeah, `.ttc`s are not supported right now. It can easily be implemented, though.

**Comment by FoggyFinder** [comment]
Thanks. I think it will be great to have ability to use `.ttc` too :)

**Comment by prepare** [comment]
see => https://github.com/LayoutFarm/Typography/commit/d4b0ca1fe38bbc3fa570ad7d4783b30513d8a520
