### ISSUE TITLE
Will this become the C# version DirectWrite or pango?

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#16]
I desperately need a text-layout engine written in raw C#. DirectWrite is windows-only. And pango is almost impossible to be compiled on mobile platforms. ( I'm exhausted with cross-compiling, makefiles and defines. It has taken me almost two month to learn and try to achieve that but completely get nothing. )

Will Typography become the C# version DirectWrite or pango? I was searching for papers and algorithms for creating a text-layout engine myself before I ran into this project. It really amazed me when I saw **Glyph Layout** in ReadMe.

I'm really looking forward to your reply! @prepare

**Comment by prepare** [comment]
Yes, I will do it my best!

**Comment by zwcloud** [comment]
Then I want to contribute definitely! 👍

Where should I start to help? Maybe build the documentation for Typography?

I'm not familiar with the underlying techniques of glyph, text-layout or font but I have much experience in DirectWrite and pango. I have create a C# warpper of DirectWrite called [DWriteSharp](https://github.com/zwcloud/DWriteSharp) a C# warpper of [stb_true_type](https://github.com/ocornut/imgui/blob/master/stb_truetype.h) called [StbTruetypeSharp](https://github.com/zwcloud/StbTruetypeSharp).

I'm now working on a raw C# GUI framework and have achieved GPU acceralated rendering on Windows, Linux (with the help of mono) and android (with the help of Xamarin.Android).

I REALLY hope I can help this project to progress at a faster speed!

**Comment by prepare** [comment]
Hello @zwcloud ,

Thank you for your attention!

I'm tackling with #10 and #11, in those developing branches.

after finish, I will clean up and refactor the code again.
(now, the code  in the dev branches is too dirty).

I can comment/suggest anything :)
