### ISSUE TITLE
GlyphTess.WinForms font polygon won't render inverted

### ISSUE THREAD

**Issue by solstice333** [LayoutFarm/Typography#172]
Environment: OSX 10.13.6, Visual Studio Community 7.7.4, mono 5.16

Initially I had trouble getting the glyph panel background to clear to white or draw anything, but I was able to refactor things so that I got rid of the `Graphics _g` instance field. Instead, I delegate all the drawing to a single paint handler and get the `Graphics` object from `PaintEventArgs`. This seems to get called fine when the panel needs re-rendering, typically when `pnlGlyph.Invalidate()` is called in the other control handlers. So things render things upside down as expected...

![screen shot 2019-02-10 at 2 50 53 am](https://user-images.githubusercontent.com/3608596/52532775-be628400-2cde-11e9-9bee-99f6d703aa80.png)

But now when I check on `Invert`the whole thing disappears and doesn't draw at all...

![screen shot 2019-02-10 at 2 51 43 am](https://user-images.githubusercontent.com/3608596/52532780-d89c6200-2cde-11e9-8cbf-120256f6d30d.png)

I've tried playing around with this code in the `DrawOutput()`...

```
    bool drawInvert = chkInvert.Checked;
            int viewHeight = this.pnlGlyph.Height;
            if (drawInvert) {
                graphics.TranslateTransform(0, viewHeight);
                graphics.ScaleTransform(1, -1);
            }
```
but can't understand why it's not flipping the image around. AFAIK, the `ScaleTransform` occurs first and mirrors/flips all the points to the negative y which is unseen. Then all the points offset back down into the view from the `TranslateTransform`. Weird. Any ideas are appreciated.

**Comment by solstice333** [comment]
Hm, seems like a bug with mono actually TBH...

**Comment by Happypig375** [comment]
Can you reproduce this behaviour after replacing calls to Typography methods with a call to draw a circle?

**Comment by prepare** [comment]
Update How to flip a glyph here =>
https://github.com/LayoutFarm/Typography/commit/147d4f550ba81d8a4b55e6a3528fc8d7ae942a63

the new one FlipY with Transformation matrix instead of flip entire Graphics object


![typo_tess_flipy](https://user-images.githubusercontent.com/7447159/52533741-ca942300-2d6a-11e9-877e-c2eb3b5d0374.png)
_and now you can read point number easily too_

**Comment by solstice333** [comment]
> Can you reproduce this behaviour after replacing calls to Typography methods with a call to draw a circle?

Yeah, commented almost all of `DrawOutput()` and replaced it with a `DrawEllipse`. When checking the invert box, the circle no longer appears within the panel view. When the invert box is, unchecked, the circle is rendered fine.

**Comment by solstice333** [comment]
> Update How to flip a glyph here =>[147d4f5](https://github.com/LayoutFarm/Typography/commit/147d4f550ba81d8a4b55e6a3528fc8d7ae942a63)
> 
> the new one Flip coord-XY-points with a transformation matrix instead of fliping entire Graphics object
> 
> ![typo_tess_flipy](https://user-images.githubusercontent.com/7447159/52533741-ca942300-2d6a-11e9-877e-c2eb3b5d0374.png)
> _and now you can read point number easily too_
> 
> please note that Flip method on the example is not optimal, it is just quick fix only

Okay, I see what the code is doing. I was about to implement the same thing just by calling a transform function on every Y point where a PointF is instantiated. The transform matrix seems like a nicer solution. Thanks. I'll give it a shot.

**Comment by solstice333** [comment]
Woohoo, the windows demo is working for osx!

![screen shot 2019-02-10 at 11 05 30 am](https://user-images.githubusercontent.com/3608596/52538149-efb17300-2d23-11e9-9adf-de6fbe7e39e1.png)

Thanks. I appreciate everyone's help.
