### ISSUE TITLE
Is there a a setting somewhere to reduce the number of triangles done in the tesselation?

### ISSUE THREAD

**Issue by solstice333** [LayoutFarm/Typography#173]
In Demo/Shared/Tesselate, is there a hard-coded value/setting somewhere to reduce the number of triangles that get drawn? Like maybe by limiting how sharp a triangle's angle is? Thanks in advance.

**Comment by prepare** [comment]
Hello, sorry for late reply

Number of triangles done in the tessellation  depend on

1. Number of point in the (input) polygon
2. Method of tessellation

in the Typography

Curve -> Flatten (1. increment flatten or 2. subdivision flatten) => polygon

Polygon -> Tess (1. SGI's Tessellate lib or 2. Triangulation lib) => triangles

----

Today I update the Tess example, (see =>https://github.com/LayoutFarm/Typography/commit/a331718bb553ba628e3afec6be12dca336205a68)

and show 2 curve flatten methods above (see pic below)

please follow the config in each button to the code

---

![2019-03-18_09-12-22](https://user-images.githubusercontent.com/7447159/54502812-197f3a80-495f-11e9-9efe-c94947ae4c22.gif)

_pic 1, 2 curve flatteners and its options_

---


Next I will add the 2 Tess options (current version is SGI's Tess lib)

**Comment by solstice333** [comment]
Thanks! I'll check it out.

**Comment by solstice333** [comment]
Hm, can't tell if subdivision and angle tolerance is doing anything in the image.

**Comment by prepare** [comment]
Hello, Today I update the tessellation part of the example.

see => https://github.com/LayoutFarm/Typography/commit/4c84b2b3541c9604d80451a0fd54ade8fc8bec82

I show 2 tess methods
1. SGI tessellation
2. Poly2Tri Triangulation 

please follow the config in each button to the code

---
![2019-03-31_13-39-05](https://user-images.githubusercontent.com/7447159/55285690-e905ba80-53ba-11e9-87f1-3e3f9e360965.gif)

_pic 2, compare 2 tess methods_

I use Poly2Tri tess for glyph contour analysis project. (see example in https://github.com/PaintLab/PixelFarm/issues/4#issuecomment-297237649)

**Comment by prepare** [comment]
Number of triangles done in the tessellation  depend on

~~1. Number of point in the (input) polygon~~
~~2. Method of tessellation~~

**Number of point in the (input) polygon**

---
Tess method has effect on triangle shape

**Comment by Verdagon** [comment]
Hey, thanks for making these changes, using Curve4Div reduced my triangle count by 57%!
