### ISSUE TITLE
Emoji Font :)

### ISSUE THREAD

**Issue by prepare** [LayoutFarm/Typography#18]
sample font 
see

https://github.com/Ranks/emojione/tree/master/assets/fonts

https://github.com/eosrei/twemoji-color-font

https://emojione.com/

**Comment by prepare** [comment]
see #52 ,

and

 https://github.com/samhocevar/emoji.wpf

**Comment by prepare** [comment]
see also https://github.com/LayoutFarm/Typography/pull/57

**Comment by samhocevar** [comment]
How about that? 😁🎆✨ (pushed in PR #59) 

![image](https://user-images.githubusercontent.com/245089/31382300-77f4a52c-adb7-11e7-9510-1e07a76f41ab.png)

**Comment by prepare** [comment]
@samhocevar ,

Thank you for your star.

I will test #59 today.

**Comment by prepare** [comment]
**Fun with Emoji !**
--- 
![typo_symbol](https://user-images.githubusercontent.com/7447159/31386243-515fdace-adf0-11e7-8644-f7c4632d9856.png)

_pic 1: Segoe UI Symbol Normal, on Win7_

---
 
![typo_symbol2](https://user-images.githubusercontent.com/7447159/31386781-3a8b85f8-adf2-11e7-8791-c19abe1fee8f.png)

_pic 2: FireFoxEmoji.ttf from https://github.com/mozilla/fxemoji_

---
@samhocevar ,
the #59 has been merged.
 please bring your 🥇

**Comment by prepare** [comment]
see https://github.com/LayoutFarm/Typography/pull/67#issuecomment-338761031

**Comment by samhocevar** [comment]
Would you like me to add Segoe UI Emoji to the test fonts directory? It’s copyrighted but everyone with Windows 8 or 10 has it and I’d say it’s [fair use](https://en.wikipedia.org/wiki/Fair_use) to have it as test material.

**Comment by prepare** [comment]
@samhocevar, 

1st thought, 
I want to add it in test material (reason => fair use).

But 2nd thought,   '_Segoe UI Emoji_' may be the _selling point_ of Win8, 10. 

so I think we would be safer not to distribute it at this moment.

---
at this time, I will look for it (locally), from my brother's computer (Win10).

:)

**Comment by samhocevar** [comment]
Okay :) Make sure you have the most recent one from Windows 10 version 1709 (MD5 `e51037f272cab7e2029ba3f69d569503`).

**Comment by prepare** [comment]
from @samhocevar 's https://github.com/LayoutFarm/Typography/pull/86#issuecomment-345479648

>This is 👩🏾‍👨🏾‍👧🏾‍👶🏾  “Family - Woman: Medium-Dark Skin Tone, Man: Medium-Dark Skin Tone, Girl: Medium-Dark Skin Tone, Baby: Medium-Dark Skin Tone” without `ccmp` ligatures:

>![image](https://user-images.githubusercontent.com/245089/32985721-fb7cef62-ccc0-11e7-8bef-90ee4ae27a04.png)

>And here it is with `ccmp`:

>![image](https://user-images.githubusercontent.com/245089/32985742-954ab2d2-ccc1-11e7-9521-06ba7bf13293.png)

>Looks almost perfect! 😁😁😁😁 Maybe some missing GPOS features? I see GPOS type 9 is not implemented yet… probably the last brick required for Emoji support.

**Comment by prepare** [comment]
Advanced Emoji ligature's GPOS was fixed : see https://github.com/LayoutFarm/Typography/pull/87
 

![image](https://user-images.githubusercontent.com/245089/32996108-a9f01da4-cd7e-11e7-84b4-d5bca20c3313.png)
