### ISSUE TITLE
Query: Extracting Glyph Character Codes from a ttf/otf font file

### ISSUE THREAD

**Issue by matthewrdev** [LayoutFarm/Typography#183]
Firstly, thanks @prepare for this incredible library. It's enabled me to build [some fantastic tools](https://www.mfractor.com/blogs/news/using-custom-fonts-in-xamarin-forms) for the Xamarin community ❤️

I'm trying to do another round of features for fonts and I'd like to be able inspect a font file and extract all glyph character codes. For example, given a font awesome ttf file, I could extract all glyphs to list their names and character codes (EG: [fa-alien == f8f5](https://fontawesome.com/icons/alien?style=light)).

@prepare If you are available, could you please email me (matthew@mfractor.com) to arrange a call on how to do this? I'm more than happy to pay for a few hours of support to get this implemented.

**Comment by prepare** [comment]
"How to list all glyph names, search glyph by name" 
---

is in the example project.

---
I will show the result first, and the show we to get it

This is screen snapshot  (today, master branch) 

I select "Font Awesome" (fa-regular-400.ttf), you can see the right-bottom box,
it is _GlyphNameListUserControl_ (GlyphNameListUserControl.cs).

In that box I demonstrate ...
1. how to list all glyph-names from font file ( in the list box)
2. search it by name ( by typing the glyph-name and press enter on that text box)

after you can a glyph you can do anything you want.


![ByCZomtFdj](https://user-images.githubusercontent.com/7447159/72492537-1d663c80-3850-11ea-9785-670fe563bd8e.gif)

_pic 1:  FontAwesome (fa-regular-400.ttf)_


----

Another example, color glyph

![XlvlPgsHfc](https://user-images.githubusercontent.com/7447159/72492515-0d4e5d00-3850-11ea-9b17-73698f0995c1.gif)
_pic 2: FirefoxEmoji.ttf_


---

About GlyphNameListUserControl
---
 
See this hint, it is easy :)


![XGHMxPa1te](https://user-images.githubusercontent.com/7447159/72492825-34f1f500-3851-11ea-98f1-e90738d107f1.gif)

_pic 3: GlyphNameListUserControl.cs_

**Comment by prepare** [comment]
similar issue is https://github.com/LayoutFarm/Typography/issues/98

**Comment by prepare** [comment]
How to get glyph-index from a unicode
---

see method typeface.LookupIndex(int codepoint, int nextCodepoint = 0)

and new demo code(https://github.com/LayoutFarm/Typography/commit/53fb16ea60cb0bcbd0284b8c8cb93493feb5ac0d)


![GlnfAiWRgZ](https://user-images.githubusercontent.com/7447159/72499344-1ea16480-3864-11ea-8f40-a0e40684f3e8.gif)




---

How to list all supported unicode inside a fontfile
---

with a given unicode,
we must 'consult' some proper character-map table inside
a font file and convert a unicode to glyph-index

so how to list all supported unicodes => we need
a new method to reverse character-map process.

so I created it ( see https://github.com/LayoutFarm/Typography/commit/f38ef8662888efad7a2d25af2af983989ade82f6)

 and demostrate here.


 
![GL9wZXs6n0](https://user-images.githubusercontent.com/7447159/72499618-f5350880-3864-11ea-922f-1583a360f88d.gif)

**Comment by matthewrdev** [comment]
Very very close now @prepare!

I've successfully pulled out all glyphs (names and unicode values) from a font file, however, the unicode character is one less than what is on fontawesome.com.

![image](https://user-images.githubusercontent.com/3260473/72516696-3e597c80-38a6-11ea-93a4-63422682481f.png)

**Comment by prepare** [comment]
related information -> see https://github.com/LayoutFarm/Typography/issues/18

**Comment by prepare** [comment]
> however, the unicode character is one less than what is on fontawesome.com.

please describe more about this

**Comment by matthewrdev** [comment]
Nevermind, it was developer error 😬 I had to change the way I mapped a glyph index to a glyph name. After fixing this, it's working perfectly!

![image](https://user-images.githubusercontent.com/3260473/72519723-0d7c4600-38ac-11ea-8aec-1cc6c3d69dd7.png)

Thank you so much! ❤️
