### ISSUE TITLE
ж

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#184]
![image](https://user-images.githubusercontent.com/19922066/73381076-1e8f7300-4300-11ea-82f7-b1c384f52b5e.png)

Font: [cyrillic-modern-nmr5.zip](https://github.com/LayoutFarm/Typography/files/4129541/cyrillic-modern-nmr5.zip)
from https://sourceforge.net/projects/cyrillic-modern/

**Comment by Happypig375** [comment]
[cyrillic-modern-nmr17.zip](https://github.com/LayoutFarm/Typography/files/4129633/cyrillic-modern-nmr17.zip)
This one fails to load in debug configuration at
https://github.com/LayoutFarm/Typography/blob/e591f60b5b96133ac05f7ba6739af778f3db2512/Typography.OpenFont/Tables.CFF/CffEvaluationEngine.cs#L407-L422

**Comment by prepare** [comment]
Thank you, I will fix it soon

**Comment by prepare** [comment]
It is ok now, (see => https://github.com/LayoutFarm/Typography/commit/a082ae69220ddaff1970e3f6aab45849dbe2f132)

![cyrillic-modern-nmr5](https://user-images.githubusercontent.com/7447159/73600973-6d9d0880-458b-11ea-87cc-54ce8d1bf2e0.png)

_cyrillic-modern-nmr5_

![cyrillic-modern-nmr17](https://user-images.githubusercontent.com/7447159/73600972-6d047200-458b-11ea-8b8e-706b30246826.png)

_cyrillic-modern-nmr17_
