### ISSUE TITLE
Bug in ClassDefTable.GetClassValue

### ISSUE THREAD

**Issue by Ollhax** [LayoutFarm/Typography#189]
In the function GetClassValue, there's a line:

`return classValueArray[startGlyph + (glyphIndex - startGlyph)];`

Which I'm pretty sure should be: 

`return classValueArray[glyphIndex - startGlyph];`

**Comment by Happypig375** [comment]
You can send a pull request directly.

**Comment by prepare** [comment]
Thank you for your report.

Now it is fixed, see=>https://github.com/LayoutFarm/Typography/commit/b7fff0c098c93edf16e91643891f699bf565346f
