### ISSUE TITLE
GlyphPathBuilder

### ISSUE THREAD

**Issue by prepare** [LayoutFarm/Typography#19]

**Comment by zwcloud** [comment]
Could you please explain interface [`IGlyphPathBuilder`](https://github.com/LayoutFarm/Typography/blob/master/Typography.OpenFont/NetCore/Typography.OpenFont/IGlyphPathBuilder.cs)? When will each method be called? What data will be provided via parameters of each method?

By the way, I know there are two implementations: `GlyphPathBuilderVxs` and `GlyphPathBuilderGdi`. But I'm don't want to guess the usage from those examples.

**Comment by prepare** [comment]
Yes.
the names may  be changed in the future.

(before full doc), just for this version.

A Cubic curve has 4 points. 
I just call them 'control points' , so it make other confuse about it

and I call ....
  first point(1st, or begin point),  
  2nd point (curve control pont), 
  3rd point  (curve control pont), 
  4th point (end point).

I think about changing its name to more meaningful one.

You can suggest new name :)


(Now, I have to go to the conference for 4-5 hours)

**Comment by prepare** [comment]
I update the code,

see the latest  [`IGlyphPathBuilder`](https://github.com/LayoutFarm/Typography/blob/master/Typography.OpenFont/NetCore/Typography.OpenFont/IGlyphPathBuilder.cs)

**Comment by zwcloud** [comment]
That's great. Almost everything about `IGlyphPathBuilder` is clear now.

But I have another question:
In the GDI winform demos, `TextPrinter` was used to print string of multiple characters-I don't quite sure about this. But it is not used and the demo can only print one character. Why?

One more suggestion:
The abstraction or design of GlyphPlan.vxs (an `object` which is actually `VertexStore`) is  bad IMHO. Do we really need an `object` type? I think there is a better way.

**Comment by prepare** [comment]
yes, I'm refactoring that

**Comment by prepare** [comment]
@zwcloud 

> In the GDI winform demos, TextPrinter was used to print string of multiple characters-I don't quite sure about this. But it is not used and the demo can only print one character. Why?

it is solved, show in pic 1.



![gdi_sample](https://cloud.githubusercontent.com/assets/7447159/23603968/b284cebc-0289-11e7-873b-07181e545add.png)

_pic 1:  now Gdi+ sample shows print a text span and opentype-feature glyph  layout._

---

> The abstraction or design of GlyphPlan.vxs (an object which is actually VertexStore) is bad IMHO. Do we really need an object type? I think there is a better way.


GlyphPlan is now struct. and the vxs field is removed.

see https://github.com/LayoutFarm/Typography/blob/master/Typography.GlyphLayout/GlyphLayout.cs

**Comment by zwcloud** [comment]
OK... I think I finally understand how [`DevGdiTextPrinter.DrawString`](https://github.com/LayoutFarm/Typography/blob/411c0b922d389e0c8e72a8305df3e243606ddf0c/Demo/Windows/GdiPlusSample.WinForms/GdiPlus/DevGdiTextPrinter.cs#L91) works now.

1. Set some properties for drawing context (GDI) and glyph layout.
2. Get/create typeface and glyph builder.
3. Layout glyphs: get layouted glyphs (`List<GlyphPlan>`).
4. For each `GlyphPlan` in the layouted glyphs,
    I. Prepare glyph data for GDI path generating later:
       (a) extract glyph points and contours from the typeface
       (b) adjust glyph points according to some settings and properties
    II. Set transformation matrix M (scale and offset) for the generated path.
    III. Generate GDI path via `GlyphPathBuilder.ReadShapes` for this single glyph.
    IV.  Transform the path by the matrix M.
    V. Render the path with GDI methods.

Am I right?

**Comment by prepare** [comment]
Yes, 
then you can optimize these steps to fit your performance

**Comment by zwcloud** [comment]
I finaly got what I need. Thank you so much for creating this fantastic library! @prepare 

layouted and tessellated glyphs of __啊abc__:
![result](https://cloud.githubusercontent.com/assets/6965758/23788488/a44dc26a-05b1-11e7-98d5-5c90cc9de012.png)

Only those source codes are used:
![typology codes](https://cloud.githubusercontent.com/assets/6965758/23788533/de051134-05b1-11e7-8f59-b3be0f872dae.png)

I have also written a demo with [CairoSharp](https://github.com/zwcloud/CairoSharp). Typography also works well.

But there are still much left to be improved. I'll arrange my ideas and post in proper issues later.

**Comment by prepare** [comment]
@prepare's note: 
Today I have fixed some important bugs (found when render 'Century' font).

---
  
 
![test_century](https://cloud.githubusercontent.com/assets/7447159/25046519/1a7ca242-215c-11e7-90ef-fda5355de788.png)

_pic 1: '2' glyph, Century font, Gdi+ version_ 

 
![test_century](https://cloud.githubusercontent.com/assets/7447159/25046658/e1f38444-215c-11e7-9431-861343bc5355.png)

_pic 2: Century font, 240 pt, NotePad[1] vs Typography  [2], see red rectangle, this is a characteristic of this glyph (starts with OFF-CURVE point and ends with OFF-CURVE point)_

**Comment by prepare** [comment]
GlyphPathBuilder is quite stable.
so I closed this.
:)
