### ISSUE TITLE
Debug NotSupportedException hit when loading XITS Math

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#194]
Font: https://github.com/alif-type/xits/blob/master/XITSMath-Regular.otf
https://github.com/LayoutFarm/Typography/blob/39e098ed1ee7851be62b549a74fdfe7c6e25693d/Typography.OpenFont/Tables.CFF/Type2InstructionCompacter.cs#L421-L425

**Comment by prepare** [comment]
Thank you for your report.

I was fixed.
see=> https://github.com/LayoutFarm/Typography/commit/f47230a8479b785afe0ca30ad501ffc137d20e0f

![xits](https://user-images.githubusercontent.com/7447159/78849571-0db95700-7a3f-11ea-837d-a13c9cc79bd4.png)

_XITS Math Regular, 48 pt_
