### ISSUE TITLE
Typography references PixelFarm

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#196]
https://github.com/LayoutFarm/Typography/blob/92a258873dc66628bd1bbf7cf24b8e28e0fdba06/PixelFarm/PaintLab.Svg/PaintLab.Svg.csproj#L149-L152

**Comment by prepare** [comment]
Thank you,

now it use 'built-in' version instead of reference to outside 


see https://github.com/LayoutFarm/Typography/commit/b5d33ac48ba48ade4e0e371c483016a05b57a500
