### ISSUE TITLE
Convert image to contour?

### ISSUE THREAD

**Issue by db300** [LayoutFarm/Typography#197]
Awsome project! Thanks a lot!
I have another question, can I use this library to convert a image to a contour?

**Comment by zwcloud** [comment]
Convert an image to a contour? What did you mean?

**Comment by db300** [comment]
Well, for example, I have a hand-writing character, and then scan it to a raster image. I need convert the image to bezier outline.

**Comment by zwcloud** [comment]
No, this is beyond the scope of Typography. I think you need somthing like [Ink Recogniser](https://azure.microsoft.com/en-in/services/cognitive-services/ink-recognizer/) or [OCR](https://en.wikipedia.org/wiki/Optical_character_recognition).

**Comment by db300** [comment]
Oh, thanks for your suggestion. But what I need is not OCR.
Any way, I can use Typography for my another project. Thanks a lot.
