### ISSUE TITLE
Typography.OpenFont.Tables.CFF.CFF.cs

### ISSUE THREAD

**Issue by db300** [LayoutFarm/Typography#198]
Line 1023:
`cff1Glyphs[i]._cff1GlyphData.Name = _uniqueStringTable[sid - Cff1FontSet.N_STD_STRINGS - 1];`
If sid - Cff1FontSet.N_STD_STRINGS - 1 >= _uniqueStringTable.Length, throw an exception.
So, I rewrite as following:
`var index = sid - Cff1FontSet.N_STD_STRINGS - 1;`
`if (index < _uniqueStringTable.Length)`
`cff1Glyphs[i]._cff1GlyphData.Name = _uniqueStringTable[sid - Cff1FontSet.N_STD_STRINGS - 1];`

**Comment by prepare** [comment]
Thank you, I will check it.

**Comment by prepare** [comment]
@db300 , could you provide a font that has that glyph-name problem?

I want to debug and make sure that the problem is from font-file, or from bug in the library

**Comment by db300** [comment]
@prepare 
[HYCuFangSongJ.zip](https://github.com/LayoutFarm/Typography/files/4590757/HYCuFangSongJ.zip)

**Comment by prepare** [comment]
note: https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5149.OTFname_Tutorial.pdf

**Comment by prepare** [comment]
I will review it again

**Comment by prepare** [comment]
HYCuFangSongJ is CID font.

This was fixed, see also => https://github.com/LayoutFarm/Typography/issues/201

-----
![N9KQOn6BqZ](https://user-images.githubusercontent.com/7447159/83123110-c413f100-a0fe-11ea-8cf2-1a05b69b4de4.gif)

_HYCuFangSongJ, no glyphname, but render by glyph index_

![Jd7hIw5P1V](https://user-images.githubusercontent.com/7447159/83123116-c4ac8780-a0fe-11ea-9996-7c546edc0b95.gif)

_HYCuFangSongJ, Hello_

**Comment by db300** [comment]
Great.
