### ISSUE TITLE
Typography.OpenFont.Glyph.cs

### ISSUE THREAD

**Issue by db300** [LayoutFarm/Typography#200]
Line: 160,
`ushort org_last_point = (ushort)(dest._contourEndPoints[org_dest_len - 1] + 1);`
Ageta Chubby Demo font, org_dest_len == 0, throw exception.

**Comment by prepare** [comment]
fixed: https://github.com/LayoutFarm/Typography/commit/b9ec4578dcee79146d298bef5a56c18155d36edb

![agenta_chubby](https://user-images.githubusercontent.com/7447159/81265891-0a30e400-906e-11ea-97fb-df5862663d66.png)
