### ISSUE TITLE
CFF CID Font with NotoSansCJK-Regular.ttc

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#201]
![image](https://user-images.githubusercontent.com/6965758/81761540-c79f5980-94fc-11ea-8919-18b5b35fd01e.png)

download the font here:
https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJK-Regular.ttc.zip

https://www.google.com/get/noto/help/cjk/

related #41

**Comment by prepare** [comment]
This is a CID font. I need a time to implement CID features.

**Comment by prepare** [comment]
NotoSansCJK-Regular.ttc is a font collection file.

Inside this font it use a collection of CFF font with CID features.

for CFF CID feature update=> see https://github.com/LayoutFarm/Typography/commit/b2787fce88848562d60ca5dfdb3aad75a084d459


---
Now we can read that font without error.
But I need to investigate more on glyph mapping, glyph access, and cmap on CID font

![cid_01](https://user-images.githubusercontent.com/7447159/83099661-1d1c5e80-a0d8-11ea-89bf-a0b128841214.png)

**Comment by zwcloud** [comment]
👍👍👍  That's great! I will try it this weekend.

**Comment by prepare** [comment]
This may help https://github.com/MatterHackers/MatterControl/issues/3807
