### ISSUE TITLE
Get unexpected rectangles when running Gdi+ Sample for DroidSansFallback font

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#202]
![image](https://user-images.githubusercontent.com/6965758/81956714-359f6a00-963e-11ea-90df-f824c0572212.png)

[download DroidSansFallbackFull.ttc](https://raw.githubusercontent.com/aosp-mirror/platform_frameworks_base/master/data/fonts/DroidSansFallbackFull.ttf)

https://github.com/aosp-mirror/platform_frameworks_base/tree/master/data/fonts

**Comment by prepare** [comment]
I've checkedthe DroidSansFallbackFull.ttc font
It contains some glyphs eg...

![fallback_3647](https://user-images.githubusercontent.com/7447159/82061653-31815400-96f3-11ea-8137-80f64c920a69.png)


I think it should be used to complement with other DroidSans  font
I will check this more

**Comment by zwcloud** [comment]
Here is a post that seems related to this issue: https://github.com/dompdf/dompdf/issues/1508#issuecomment-321990907

**Comment by prepare** [comment]
I will  add typeface-fallback mechanism later

**Comment by prepare** [comment]
Languaue-Detection => Auto-Font-Switching and Font-fallback,  Work-in-Progress
---


![font_fallback1](https://user-images.githubusercontent.com/7447159/83974872-a6266780-a91a-11ea-915b-e92f0bd13e21.png)

**Comment by prepare** [comment]
Script-Detection => Auto-Font-Switching and Font-fallback,  Work-in-Progress
---

こんにちは, 你好, 여보세요 abc 0123  شمس حب 
 
![font_fallback1](https://user-images.githubusercontent.com/7447159/83975034-978c8000-a91b-11ea-9d42-b80c35b4b812.png)



----

شمس حب น้ำน้ำ こんにちは

![font_fallback2](https://user-images.githubusercontent.com/7447159/83974994-58f6c580-a91b-11ea-8d26-4af04cdf4bf4.png)

**Comment by prepare** [comment]
Gdi+ example,  Work-in-Progress
---

![auto_typeface_switching](https://user-images.githubusercontent.com/7447159/86952467-3dcae000-c17d-11ea-9257-f993bbd90290.png)
_auto typeface-switching_
