### ISSUE TITLE
Getting the Font & Character Details

### ISSUE THREAD

**Issue by dansiegel** [LayoutFarm/Typography#203]
I've been trying to use the Typography.OpenFont project and I'm not really seeing a reliable way of reading the font to get the basic information about the font. Specifically I'm looking for:

- The PostScript Name... Current I just get the full name. As an example if reading `Font Awesome 5 Free Regular`, I get that in the name property but I'm not getting the proper PostScript name which would be `FontAwesome5Free-Regular`
- The Font Version
- In some fonts like Font Awesome I can see the Font name in the PostTable but other fonts like Material Icons this appears to be null. 
- In the PostTable's Glyph Names it seems to return a Dictionary<ushort, string> however the ushort is not the proper numeric value for the unicode character, and I'm not seeing how to properly get map this to the unicode character.

Any pointers would be greatly appreciated.

**Comment by prepare** [comment]
Could you provide an example font for me to test?

**Comment by prepare** [comment]
see also https://github.com/LayoutFarm/Typography/issues/183

**Comment by dansiegel** [comment]
Thanks @prepare I'll check out 183... in the mean time here are two fonts I was playing with. Both of these the PostTable.GlyphNames are null.

[fonts.zip](https://github.com/LayoutFarm/Typography/files/4665960/fonts.zip)

**Comment by dansiegel** [comment]
183 solved my issue with getting the correct Unicode character, thanks for that.

**Comment by prepare** [comment]
Early help:

1. How to get PostScript Name and Font Version:

for material icon, see  this code

![material_icon1](https://user-images.githubusercontent.com/7447159/82632033-501aaa00-9c21-11ea-9c0f-daefb2e2cf9d.png)

2. Post table of material icon use version 3.0, so no glyph names.
 
see also https://stackoverflow.com/questions/23185221/getting-the-glyph-name-from-a-ttf-or-otf-font-file

then I will find how to get glyph-name from other places

**Comment by prepare** [comment]
note:
font-awesome: https://fontawesome.com/cheatsheet

unicode CLDR name: 
http://cldr.unicode.org/translation/characters-emoji-symbols/short-names-and-keywords
http://unicode.org/reports/tr51/

**Comment by prepare** [comment]
for 1 and 2  How to get PostScript Name and Font Version:

see https://github.com/LayoutFarm/Typography/commit/526bfa5a9d1214c628040227f31b2869085aa780#diff-75f31004e6a0db92560eaf11f6eab115R137

for 3.
Post table of material icon use version 3.0, so no glyph names inside a font.

for 4. resolved with  https://github.com/LayoutFarm/Typography/issues/183 (https://github.com/LayoutFarm/Typography/issues/203#issuecomment-632475590)
