### ISSUE TITLE
Surrogates after whitespaces should revert to WordKind Unknown in TextBreak

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#206]
```cs
var breakList = new System.Collections.Generic.List<Typography.TextBreak.BreakAtInfo>();
var breaker = new Typography.TextBreak.CustomBreaker();
breaker.SetNewBreakHandler(v => breakList.Add(new Typography.TextBreak.BreakAtInfo(v.LatestBreakAt, v.LatestWordKind)));
breaker.BreakWords("😀");
; // breakList is { BreakAtInfo(2, Unknown) }
breakList.Clear();
breaker.BreakWords(" 😀");
; // breakList is { BreakAtInfo(1, Whitespace), BreakAtInfo(3, Whitespace) }
breakList.Clear();
breaker.BreakWords("a😀");
; // breakList is { BreakAtInfo(1, Text), BreakAtInfo(3, Text) }
```

**Comment by prepare** [comment]
Thank you!

fixed, see=> https://github.com/LayoutFarm/Typography/commit/2ff55d764cae9ee6b6a1546650fc81fe38326b78

**Comment by Happypig375** [comment]
Shouldn't you update e.g. `char.IsPunc` to use `string.IsPunc` to deal with surrogates correctly?

**Comment by prepare** [comment]
Char.IsPunctuation() has 2 overloads

https://docs.microsoft.com/en-us/dotnet/api/system.char.ispunctuation?view=netcore-3.1

**Comment by Happypig375** [comment]
Yes, that is what I mean. The `string, int` overload deals with surrogates correctly.

**Comment by prepare** [comment]
The engine handles the char[] buffer, 
so I choose the Char.IsPunctuation(char c) 
(not turn back to string).

**Comment by Happypig375** [comment]
Hmm. On testing, I might be wrong. Nevermind.
