### ISSUE TITLE
Where is `GlyphLayout.ReadOutput` now?

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#207]
I'm upgrading the Typography used in my project to latest master. And just ran into an issue: `GlyphLayout.ReadOutput()` is gone. I need the function to calculate offsetX for `UnscaledGlyphPlanList`, Otherwise the layouted glyph characters will all be rendered at (0, OffsetY), because OffsetX is always zero.

https://github.com/LayoutFarm/Typography/blob/58a6a44259f22208739976cf7e0655cabd2e1c81/Typography.GlyphLayout/GlyphLayout.cs#L216-L260

The essential part in code above is `cx += glyphPos.advWidth; `.

Did I miss something? Or should I calculate OffsetX myself?

**Comment by Happypig375** [comment]
https://github.com/LayoutFarm/Typography/commit/c0e8a0bd14cb468654d3a4d512167f78207c0309#diff-b705c14388c05643560a455e65eaf449

**Comment by Happypig375** [comment]
>673: Clearify GlyphLayout
>
>remove PixelScale, FontSizeInPoints, GlyphPlanList,
UsePxScaleOnReadOutput from GlyphLayout.
>
>Make it more clearly.
>
>Output from GlyphLayout is in unscaled version.
>
>Then we scale it to fit our need.

**Comment by zwcloud** [comment]
OK. I have read lastest GlyphLayout.cs throughly. And  judging from the code, `GlyphLayout` no longer calculates offsetX (apply advanceX according to PositionTechnique) when building (Unscaled)GlyphPlan. This is really a breaking change. 😂

**Comment by zwcloud** [comment]
Understood! Since `UnscaledGlyphPlan.OffsetX` is changed to a `short`. It's not suitable to save accumulated advanceX into that field. (Old `GlyphPlan.OffsetX` is int.)

**Comment by zwcloud** [comment]
Done upgrading Typography in my project in these commits.

https://github.com/zwcloud/ImGui/commit/6dbe4223ed570650710a453b707b5b2eeb3a7c28
https://github.com/zwcloud/ImGui/commit/f2d86e6f3d80d604e2e3fe46df13c4ae9df9ccb7
https://github.com/zwcloud/ImGui/commit/94674bf5e2afb0d1cbf24b0b51f900ada4c92b47
