### ISSUE TITLE
C# implementation of path rendering

### ISSUE THREAD

**Issue by acaly** [LayoutFarm/Typography#208]
Thank you so much for this great library! I love the new Typography.One.

I plan to use it in one of my personal projects to draw text with Direct3D 11. I am working on a IGlyphTranslator that converts the glyph data to triangle list (polygon triangularation), which can then be used to create the VertexBuffer. I wonder if that's the desired way of doing it. Does Typography already provide similar function somewhere?

**Comment by prepare** [comment]
Thank you for your interest.

Typography.One does not have drawing functions.

The user must do it by themselves.

---

But I provide some examples that do the polygon triangulation  like this ... 

![2019-03-31_13-39-05](https://user-images.githubusercontent.com/7447159/55285690-e905ba80-53ba-11e9-87f1-3e3f9e360965.gif)

_compare 2 tess methods (from https://github.com/LayoutFarm/Typography/issues/173#issuecomment-478316751)_

see this example here=> https://github.com/LayoutFarm/Typography/tree/master/Demo/Windows/GlyphTess.WinForms


---

I'm working on glyph-rendering technique with GLES.

There are some advanced examples of Glyph rendering with VBO, Atlas-Texture-Base Glyph rendering techniques. But they are not stable. All of them are inside https://github.com/PaintLab/PixelFarm

**Comment by acaly** [comment]
Thanks! That looks great. I will check them out.
