### ISSUE TITLE
Is this a correct way to calculate the actual line-height of a typeface in specific font size?

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#217]
public static double GetLineHeight(Typeface typeFace, double fontSize)
        {
            var scale = typeFace.CalculateScaleToPixelFromPointSize((float)fontSize);
            return (typeFace.Ascender - typeFace.Descender + typeFace.LineGap) * scale;
        }

I got a very big result (about 84) for ProggyClean.ttf and font size 10 at f299557855a8e6935f43f751c09320b46f934510.

And in the demo:
![GdiPlusSample WinForms_2020-11-09_21-49-45](https://user-images.githubusercontent.com/6965758/98549279-8504e100-22d5-11eb-8ba9-10fc5dbfe6c7.png)

[ProggyClean.zip](https://github.com/LayoutFarm/Typography/files/5510880/ProggyClean.zip)

**Comment by prepare** [comment]
Sorry for late reply  
I will check it soon.

**Comment by prepare** [comment]
Fixing preview, WIP

![proggy](https://user-images.githubusercontent.com/7447159/99536233-aa33d680-29dc-11eb-9a39-f1c33c4f5602.png)

**Comment by prepare** [comment]
ProggyClean does not support typographic metric. 

Fixed, see https://github.com/LayoutFarm/Typography/commit/3eb846496d8543b2a9664150ffebfedc404b9de2
