### ISSUE TITLE
[Question] Type2 hintmask and cntmask

### ISSUE THREAD

**Issue by QuantumDeveloper** [LayoutFarm/Typography#222]
Hi. 
I am also working on my own CFF parser and despite that I read documentation a lot of times, I still cannot understand one thing regarding hintmask and cntmask:
Documentation is not very clear about how to determine which amount of bytes should be read after we detect hintmask or cntmask operator. And because of this my parser is breaking down when finding these operators.

Can you please explain the logic behind this? Unfortunately I didnt find answer in google. Would be appreciate for your help.

**Comment by prepare** [comment]
Haha

Typography.OpenFont.CFF.CffEvaluationEngine  reads hintmask and cntmask instructions but the engine does not implement
the those hint instructions yet=> it skips all hint instructions.

:)

**Comment by prepare** [comment]
Ref: https://adobe-type-tools.github.io/font-tech-notes/pdfs/5177.Type2.pdf

**3.1  Type 2 Charstring Organization**
 
The sequence and form of a Type 2 charstring program may be represented as:

          w? {hs* vs* cm* hm* mt subpath}? {mt subpath}* endchar

Where:

w = width
hs = hstem or hstemhm command
vs = vstem or vstemhm command
cm = cntrmask operator
hm = hintmask operator
mt = moveto (i.e. any of the moveto) operators
subpath = refers to the construction of a subpath (one complete closed contour), which may include hintmask operators where appropriate.

and the following symbols indicate specific usage:
     *  zero or more occurrences are allowed
     ?  zero or one occurrences are allowed
     + one or more occurrences are allowed
    { } indicates grouping

---
...
...
2) Hints: zero or more of each of the following hint operators, in exactly the following order:
**hstem, hstemhm, vstem, vstemhm, cntrmask, hintmask**.
Each entry is optional, and each may be expressed by one or more occurrences of the operator. 

The hint operators cntrmask and/or hintmask **must not** occur if the charstring has no stem hints.

**Comment by QuantumDeveloper** [comment]
I tried to implement behaviour as described in docs and I still facing a parsing issues.
I will describe you what I did step by step. Maybe you will find what I am missing here.
1. I am accumulating stem count based on operands count:
``` 
                       default:
                            switch (token)
                            {
                                case (ushort)OperatorsType.vstem:
                                case (ushort)OperatorsType.hstem:
                                case (ushort)OperatorsType.hstemhm:
                                case (ushort)OperatorsType.vstemhm:
                                    stemCount+=operands.Count;
                                    break;
                            }
                            
                            var command = new Command();

                            command.@operator = bytesToOperatorMap[token];
                            command.operands = operands;

                            commands.Add(command);
                            break;
```
2. When I am facing hintmask or cntmask I do the following:
```
switch(token)
...
                        case (ushort)OperatorsType.hintmask:
                        case (ushort)OperatorsType.cntrmask:
                            stemCount /= 2;
                           
                            if (stemCount == 0) stemCount = 1;
                            var bytesToRead = Math.Ceiling((double) stemCount / 8);
                            for (int i = 0; i < bytesToRead; ++i)
                            {
                                var maskByte = mainStack.Pop();
                            }

                            stemCount = 0;
                            break;
```
And even with this algorithm I am facing with issue.
I am takштп into account the width, which could be the first argument for hints by dividing by 2. It will round to the lowest integer value.

I debug your code and you somehow calculating that you need to read exactly 2 bytes (for curtain glyphs), where I am always read only 1 byte. 
Obviously, your code is working correctly, but I cannot understand where and what I am missing.
If you could help me with it and point what is worng, I would be very appreacite.
@prepare

**Comment by prepare** [comment]
1) please give put some code region of **my** implementation. 
> ".. you somehow calculating that you need to read exactly 2 bytes  (for curtain glyphs), where I am always read only 1 byte."



2) Did you stop stem counting correctly? (after enter into shape instructions region)

https://github.com/LayoutFarm/Typography/blob/b0d851793510ccafda2a62cf810f9f7870325746/Typography.OpenFont/Tables.CFF/Type2CharStringParser.cs#L886

**Comment by prepare** [comment]
3. from your code, 
4.

**Comment by prepare** [comment]
from my implementation  when _hintStemCount ==0

https://github.com/LayoutFarm/Typography/blob/b0d851793510ccafda2a62cf810f9f7870325746/Typography.OpenFont/Tables.CFF/Type2CharStringParser.cs#L1072

```
   if (_hintStemCount == 0)
            {
                if (!_foundSomeStem)
                {
                    _hintStemCount = (_current_integer_count / 2);
                    if (_hintStemCount == 0)
                    {
                        return;
                    }
                    _foundSomeStem = true;//?
                }
                else
                {
                    throw new NotSupportedException();
                }
            }

```

please check your code

```
switch(token)
...
                        case (ushort)OperatorsType.hintmask:
                        case (ushort)OperatorsType.cntrmask:
                            stemCount /= 2;
                           
                            if (stemCount == 0) stemCount = 1;
                            var bytesToRead = Math.Ceiling((double) stemCount / 8);
                            for (int i = 0; i < bytesToRead; ++i)
                            {
                                var maskByte = mainStack.Pop();
                            }

                            stemCount = 0;
                            break;
```

**Comment by QuantumDeveloper** [comment]
> 1. Did you stop stem counting correctly? (after enter into shape instructions region)

I think yes. Because As far as I can see, you stop stem count almost on all operators except stem operators. This is what I am doing exactly. All operands before stem commands in accumulating in array and then I add them to the stem count. I do this only if I faced with one of stem operators.
```
switch (token)
                            {
                                case (ushort)OperatorsType.vstem:
                                case (ushort)OperatorsType.hstem:
                                case (ushort)OperatorsType.hstemhm:
                                case (ushort)OperatorsType.vstemhm:
                                    stemCount+=operands.Count;
                                    break;
                            }
```
And after I found hintmask/cntmask operator, I set stem count to 0.

Also, I didnt see that you ever fall in case when you when this condition is executing:
```
                   if (_hintStemCount == 0)
            {
                if (!_foundSomeStem)
                {
                    _hintStemCount = (_current_integer_count / 2);
                    if (_hintStemCount == 0)
                    {
                        return;
                    }
                    _foundSomeStem = true;//?
                }
                else
                {
                    throw new NotSupportedException();
                }
            }
```

At least not in fonts which I have tested.

But maybe I am missing something and I need to calculate stem count somehow differently? 
Maybe I can provide my test font and glyph index that is failing and you can give me more info then?

**Comment by prepare** [comment]
Yes, please give me the test font and glyph index.

**Comment by prepare** [comment]
you can send test font to me (wintercoredev "at" gmail.com) 
or
if it is not private font you can zip and post it the the comment section here

**Comment by QuantumDeveloper** [comment]
[Glametrix-oj9A.zip](https://github.com/LayoutFarm/Typography/files/6121472/Glametrix-oj9A.zip)
Glyph index 554. When it come to hintmask, it should read 2 bytes

**Comment by prepare** [comment]
I downloaded the font and it removed it.


Thank you.  give me a time to test it.
(Glyph index 554)

**Comment by QuantumDeveloper** [comment]
Also, I would like to know why you are doing decrement in callsubr/callgsubr operatos for  `_current_integer_count--`
I didnt find anything about this in docs.

**Comment by prepare** [comment]
(developing ...)

Hello, This is your glyph-554 of Glametrix font

![glyph_554](https://user-images.githubusercontent.com/7447159/110810649-94625e00-82b8-11eb-98a4-56bf2973a000.png)
_glyph 554 Glametrix (cff font)_

---
and this is a (part of) raw byte[]  of a glyph-554 instructions (Type2 CFF CharString)
![DmqvOKXeRO](https://user-images.githubusercontent.com/7447159/110812452-32a2f380-82ba-11eb-8098-429f43b0bc62.png)

---
After the raw buffer is parsed, the parser translate it to these instructions...

```
[0] GlyphWidth 162
[1] 0 [2] 50 [3] 170 [4] 50 [5] 190 [6] 20 [7] 90 [8] 60 [9] hstemhm
[10] 55 [11] 65 [12] 48 [13] 60 [14] 74 [15] 68 [16] -62 [17] 60 [18] 57 [19] 65 [20] vstem
[21] hintmask2 10101000000000000000000000000
[22] 308 [23] 570 [24] rmoveto
[25] 49 [26] hlineto
[27] 8.900391
[28] 1.099609
[29] 1.099609
[30] 8.900391
[31] hvcurveto
[32] 49 [33] -49 [34] vlineto
[35] -9.900391
[36] -2.099609
[37] -2.099609
[38] -9.900391
[39] hvcurveto
[40] -140 [41] -49 [42] rmoveto
[43] 49 [44] hlineto
[45] 8.900391
[46] 1.099609
[47] 1.099609
[48] 8.900391
[49] hvcurveto
[50] 49 [51] -49 [52] vlineto
[53] -9.900391
[54] -2.099609
[55] -2.099609
[56] -9.900391
[57] hvcurveto
[58] hintmask2 11101010100000000000000000000000
[59] -113 [60] -619 [61] rmoveto
[62] 136 [63] hlineto
[64] 107.4004
[65] 70.59961
[66] 54 [67] 81 [68] 81 [69] -71.59961
[70] 54 [71] -108.4004
[72] hvcurveto
[73] -71 [74] 210 [75] -65 [76] hlineto
[77] 65 [78] -430 [79] rmoveto
[80] 170 [81] 75 [82] vlineto
[83] 64.2002
[84] 41.7998
[85] -34 [86] -51 [87] -51 [88] -42.7998
[89] -34 [90] -65.2002
[91] hvcurveto
[92] 230 [93] -50 [94] rmoveto
[95] 65 [96] 480 [97] -65 [98] hlineto
[99] endchar
```

_glyph 554 instructions_

---
Your main problem is **How to find number of bytes for hint mask**?
so lets check only first 22 instructions

**Comment by prepare** [comment]
Another question:
> ..why you are doing decrement in callsubr/callgsubr operatos for  `_current_integer_count--`



![debug6](https://user-images.githubusercontent.com/7447159/110822194-659db500-82c3-11eb-9cc7-a2101767e6a7.png)



Ans: it is my implementation => because callsubr/callgsubr use 1 parameter , so I remove its parameter from..
```
Type2Instruction inst = _insts.RemoveLast();
```
so  under __doStemCount_ => I need to do reduce 1 _current_integer_count.

```
 if (_doStemCount)
 {
        _current_integer_count--;
  }
```

**Comment by prepare** [comment]
You can dump other instructions of a CFF glyph =>

![debug7](https://user-images.githubusercontent.com/7447159/110826352-91bb3500-82c7-11eb-902d-5b1268c913ea.png)

```
 if (dbugCurrentGlyphIndex == 554)
            {
                _insts.dbugDumpInstructionListToFile("glyph_554.txt");
            }
```

**Comment by QuantumDeveloper** [comment]
@prepare 
Thanks a lot. Your answers were really helpful. I think I found all bugs in parser. At least I hope.
But I still have some questions:
1. Where in your code I can find Intrerpretation of `vvcurveto`, `hhcurveto` and other such operators? I am not sure that my implementation of interpreter process these operators fully correctly.
2. Do you know where I can find otf fonts with CFF Type1, CFF2 Type1, CFF Type2, OTF with TTF inside? Because for now all fonts I can find is CFF with Type2.
Would be very appreciate for help.

**Comment by prepare** [comment]
>1. Where in your code I can find Intrerpretation of vvcurveto, hhcurveto and other such operators?

see:  https://github.com/LayoutFarm/Typography/blob/master/Typography.OpenFont/Tables.CFF/CffEvaluationEngine.cs

for example `vvcurveto` >
https://github.com/LayoutFarm/Typography/blob/b0d851793510ccafda2a62cf810f9f7870325746/Typography.OpenFont/Tables.CFF/CffEvaluationEngine.cs#L1002

for example  `hhcurveto`  >
https://github.com/LayoutFarm/Typography/blob/b0d851793510ccafda2a62cf810f9f7870325746/Typography.OpenFont/Tables.CFF/CffEvaluationEngine.cs#L571


---
>2. Do you know where I can find otf fonts with CFF Type1, CFF2 Type1, CFF Type2, OTF with TTF inside? Because for now all fonts I can find is CFF with Type2

I don't have a complete set. Most font I have is CFF with Type2.

please check these  further
- "Adobe Type Tools" https://github.com/adobe-type-tools
- "Adobe Font Development Kit for OpenType" https://github.com/adobe-type-tools/afdko
- "FreeType" https://www.freetype.org/ , https://github.com/freetype/freetype
