### ISSUE TITLE
How to get the line height of a layouted text?

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#23]
For example, 

````C#
class MyTextPrinter : DevTextPrinterBase { ... }
//...
MyTextPrinter printer = new MyTextPrinter();
printer.FontFilename= "D:\msjh.ttf";
printer.FontSizeInPoints = 12;
printer.DrawString(new []{'A', 'B', 'C', '啊'}, 0, 0);
````

How to get the actual line height of the layouted and printed text? Is it just `printer.FontSizeInPoints`?
(I know the function of `GlyphLayout` is quite limited and can only layout text characters in one line.)

**Comment by zwcloud** [comment]
I just tried and it seems the line height is `printer.FontSizeInPoints`.

**Comment by prepare** [comment]
This is early fix. 
It will be refactored later.

see How to calculate LineHeight here

https://github.com/LayoutFarm/Typography/blob/a7af7e944b9eecbd8e838953c727a2f2fc5b5763/Demo/Windows/GdiPlusSample.WinForms/GdiPlus/DevGdiTextPrinter.cs#L65


![gdi_sample_lineheight](https://cloud.githubusercontent.com/assets/7447159/23942762/ec9b6c1a-099f-11e7-8b74-5196f909b11c.png)

_pic 1: LineHeight test on multiple font size_

**Comment by prepare** [comment]
measure a string is easy.
(https://github.com/LayoutFarm/Typography/blob/4d6811853dc7938bec02e0da9a4328e528cda762/Demo/Windows/GdiPlusSample.WinForms/GdiPlus/DevGdiTextPrinter.cs#L233)

![measure_string](https://cloud.githubusercontent.com/assets/7447159/24000100/e56c12ee-0a8c-11e7-8eb1-5c738ca47bdb.png)

_pic 2: shows baseline, ascending, descending, line-spacing box_
