### ISSUE TITLE
You have a big plan, but your personal ability is very limited. It is recommended to focus on the 2D library and font library first.

### ISSUE THREAD

**Issue by sgf** [LayoutFarm/Typography#233]
You have a big plan, but your personal ability is very limited. It is recommended to focus on the 2D library and font library first. Put the others aside for now. Otherwise, all projects will stagnate.
In addition, the projects are too scattered. It is recommended to merge them into 2-3  library, abandon the old .net framework support, and only support the latest .net version such as the current .net 8.0.

**Comment by zwcloud** [comment]
Pull requests are welcome. Also you can fork this repo and do it yourself.

**Comment by sgf** [comment]
At present, I have only forked pixelFarm. But whether in terms of knowledge or understanding and mastery of technology, I cannot be compared with the author.
At the same time, the open source library should be led by the author. Even if the author gradually withdraws from coding due to life or time reasons, he can be responsible for management. Or at least the warehouse must be led by the original author.
Otherwise, there will be a split head problem, that is, the update of the branch cannot be merged into the main warehouse, so that the main warehouse cannot be Get iterated and improved.

**Comment by sgf** [comment]
Because branches are always scattered, even if they have some progress, they cannot be merged together.
