### ISSUE TITLE
Android issue: BinaryReader.BaseStream.Seek is not supported.

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#25]
I'm trying Typography with Xamarin.Android but run into the issue: a `System.NotSupported ` exception was thrown when executing [`reader.BaseStream.Seek(this.Header.Offset, SeekOrigin.Begin)`](https://github.com/LayoutFarm/Typography/blob/fef175175c5eaf78050fc885f36f38b13f9dd736/Typography.OpenFont/NetCore/Typography.OpenFont/Tables/TableEntry.cs#L21).

I'm asking about it in gitter of Xamarin.Android, but I think it may also related to Typography itself. But it work well in .NET core. 😕

**Comment by zwcloud** [comment]
I just tried to use a `MemoryStream` instead of a `FileStream`. It fixed the `NotSupportedException` but still got stuck.

````C#
var data = File.ReadAllBytes(@"D:\TestFonts\CompositeMS.ttf");
var str = Convert.ToBase64String(data);
var tmpFontFileData = Convert.FromBase64String(str);
var memoryStream = new MemoryStream(tmpFontFileData);

// then, create the OpenFontReader in a TextPrinter
var reader = new OpenFontReader();
CurrentTypeFace = reader.Read(fs);

````

All the code above executes without any error. But then a NRE is thrown when it executes to here:
![](http://i.imgur.com/aobDtlo.png)

@prepare You may try it yourself by using a `MemoryStream` instead of the `FileStream` like what I have done.

**Comment by zwcloud** [comment]
I found it only happens with `CompositeMS.ttf`. So it may be related to the font file? But apparently it is another bug of Typography.

**Comment by prepare** [comment]
Thank you.
I will look at that soon.

**Comment by prepare** [comment]
> I just tried to use a MemoryStream instead of a FileStream. It fixed the NotSupportedException ...

Do I still need to fix that 'Seek' problem?

**Comment by zwcloud** [comment]
No. It's better to fix that after I finishing the Android demo so you can repoduce the issue easily. The 'Seek' problem only happens with Xamarin.Android.
