### ISSUE TITLE
Possible Bug of Typography.OpenFont.IO.ByteOrderSwappingBinaryReader

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#29]
When I'm testing a ttf file with Typography, `Typography.OpenFont.IO.ByteOrderSwappingBinaryReader.ReadInt16` throw an `System.IO.EndOfStreamException`: 'Unable to read beyond the end of the stream.'

Stack:

	Typography.OpenFont.IO.ByteOrderSwappingBinaryReader.ReadInt16() Line 59	C#
 	Typography.OpenFont.Tables.GPOS.ValueRecord.ReadFrom(System.IO.BinaryReader reader, ushort valueFormat) Line 107	C#
 	Typography.OpenFont.Tables.GPOS.ValueRecord.CreateFrom(System.IO.BinaryReader reader, ushort valueFormat) Line 158	C#
 	Typography.OpenFont.Tables.GPOS.PairSetTable.ReadFrom(System.IO.BinaryReader reader, ushort v1format, ushort v2format) Line 49	C#
 	Typography.OpenFont.Tables.GPOS.LookupTable.ReadLookupType2(System.IO.BinaryReader reader) Line 468	C#
 	Typography.OpenFont.Tables.GPOS.LookupTable.ReadRecordContent(System.IO.BinaryReader reader) Line 245	C#
 	Typography.OpenFont.Tables.GPOS.ReadLookupListTable(System.IO.BinaryReader reader, long lookupListBeginAt) Line 170	C#
 	Typography.OpenFont.Tables.GPOS.ReadContentFrom(System.IO.BinaryReader reader) Line 69	C#
 	Typography.OpenFont.Tables.TableEntry.LoadDataFrom(System.IO.BinaryReader reader) Line 22	C#
 	Typography.OpenFont.OpenFontReader.ReadTableIfExists<Typography.OpenFont.Tables.GPOS>(Typography.OpenFont.Tables.TableEntryCollection tables, System.IO.BinaryReader reader, Typography.OpenFont.Tables.GPOS resultTable) Line 162	C#
 	Typography.OpenFont.OpenFontReader.Read(System.IO.Stream stream, Typography.OpenFont.ReadFlags readFlags) Line 91	C#

The ttf font file I'm using:
[DroidSans.zip](https://github.com/LayoutFarm/Typography/files/854170/DroidSans.zip). I forgot where it is from. But it can be opened by the Windows Font Viewer so it should be valid.

**Comment by zwcloud** [comment]
I just tried msjh.ttf in *Demo/Windows/TestFonts* and it works well. So it seems to be another file-specific bug.

**Comment by prepare** [comment]
I will tackle this soon.

**Comment by zwcloud** [comment]
Thanks!
But  don't give yourself too much pressure. I found you commit many changes and fixes a day. Just don't forget to take a rest whenever you need.

**Comment by prepare** [comment]
@zwcloud, Thank you.

The bug is DataType error,

I fixed it, Now it can read DroidSan.

see =>https://github.com/LayoutFarm/Typography/commit/bbeaf25e1480703edf4e9b380b02cb77327c71ba

I'm fixing other areas

**Comment by prepare** [comment]
fix data type,

see=>a3a9b57d6453be7fa508b6fb7d0873ef41ac7428

![fix_droidsans](https://cloud.githubusercontent.com/assets/7447159/24106632/0e5c9224-0dbb-11e7-807f-06891f255b0e.png)
