### ISSUE TITLE
implement other essentail tables

### ISSUE THREAD

**Issue by prepare** [LayoutFarm/Typography#3]
@vidstige ,  please comment about this how-to-build-each-table

**OpenType Layout**
(https://www.microsoft.com/typography/otspec/ttochap1.htm)
1. Name: created (https://github.com/prepare/FontRasterizer/blob/master/OpenTypeReader/Tables/NameEntry.cs)
2. Kern: created (https://github.com/prepare/FontRasterizer/blob/master/OpenTypeReader/Tables/Kern.cs)
3. Glyph Substitution table (GSUB) :developing ...
4. the Glyph Positioning table (GPOS): developing ...
5. the Baseline table (BASE): developing ...
6. the Justification table (JSTF), and 
7. the Glyph Definition table (GDEF): developing ...

---

I've changed how to create each table.
see
 https://github.com/prepare/FontRasterizer/blob/master/OpenTypeReader/OpenTypeReader.cs#L46
1. All tables are subclass of TableEntry (https://github.com/prepare/FontRasterizer/blob/master/OpenTypeReader/Tables/TableEntry.cs)
2. First, Load all as UnreadTableEntry 
   ((https://github.com/prepare/FontRasterizer/blob/master/OpenTypeReader/OpenTypeReader.cs#L58)
3. and substitute some of them with actual table  
   (https://github.com/prepare/FontRasterizer/blob/master/OpenTypeReader/OpenTypeReader.cs#L63)
4. I have created a Kern table and Name table

**Comment by vidstige** [comment]
I try to never use abstract classes for cleanest possible design. In this case I see no point in the proposed changes. I would prefer to load the kern and name tables normally.

**Comment by vidstige** [comment]
I think highest prio is to get a proper rendering working again in master, then I will look at kerning, etc.

**Comment by prepare** [comment]
> I try to never use abstract classes for cleanest possible design.

Why?,
Do you have a reference for the design guideline? 
(so I will understand.)

I understand that the class should not so 'deep' in inheritance hierarchy.
this is 2 levels, and private class. 
Is it ok or not? , or should use interface instead?

**Comment by prepare** [comment]
The quick .....
![string](https://cloud.githubusercontent.com/assets/7447159/19414753/bec50254-9381-11e6-8ebb-07b23d84eb90.png)

---
Kern

![kern] (https://cloud.githubusercontent.com/assets/7447159/19415089/7d3ae864-938e-11e6-94b1-4817b327832a.png)

**Comment by vidstige** [comment]
There is no design guide line, but you can consider the existing code (some is hacky) to be reference. E.g here you have changed into an abstract base class where there was none before. 

Looks great with kerning! I feel you are not helping working towards making your repo use a nuget package, so I will leave that for now and keep working on the NRasterizer.
