### ISSUE TITLE
Upgrade to VS2017

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#30]
I think the project should be upgraded to VS2017 since [it has been released](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes).

The most important thing is that the support for .NET Standard(including .NET core) is greatly improved in VS2017. Also some project structures are changed. For example, `project.json` and `*.xproj` are no longer used. Instead, `*.csproj` is used for all C# projects in VS2017.

VS2017 can easily upgrade VS2015 solution and projects automatically. And I have done that on my machine. 

I have been using VS2017 RC and RTM for several months. It provides more flexible installation and is smaller and quicker than the big VS2015. BTW, the android projects using Typography is written with VS2017--I can't install VS2015 on my machine because the remaining disk space is not enough.

**Comment by prepare** [comment]
Ready for VS2017

5b80aca3b38dda8175f6b9789d474cd924ee09ff
