### ISSUE TITLE
Does Typography support Xamarin.Forms yet?

### ISSUE THREAD

**Issue by Emasoft** [LayoutFarm/Typography#38]
Does Typography support Xamarin.Forms yet?

**Comment by prepare** [comment]
at this time, => no 

:)

**Comment by zwcloud** [comment]
@Emasoft It's easy to implement a renderer based on Typography on ANY platform supports C#. But currently there is no existing demo for Xamarin.Form.

But I appreciate it if you create a demo on Xamarin.Form! Just follow the demos in [__Demo/Windows__][1].

https://github.com/LayoutFarm/Typography/tree/master/Demo/Windows

**Comment by prepare** [comment]
Examples:
1) **CSharpMath** (developing): : https://github.com/verybadcat/CSharpMath/issues/1#issuecomment-393211266  :+1: 

   Xamarin Form =>

    Read Math Glyphs with Typography => Render with Skia on Xamarin Form
