### ISSUE TITLE
OpenFontReader NullReferenceException, CvtTable

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#40]
https://github.com/LayoutFarm/Typography/blob/1b4f7c82f02c6d83f716603c1bf9bd684f83c9bc/Typography.OpenFont/OpenFontReader.cs#L134

```C#
CvtTable cvtTable = ReadTableIfExists(tables, input, new CvtTable());

typeface.ControlValues = cvtTable.controlValues;
```

The returned `cvtTable` can be `null` and that causes a NRE on the next line.

Tested with [unifont-9.0.06.ttf](http://unifoundry.com/pub/unifont-9.0.06/font-builds/unifont-9.0.06.ttf) from http://unifoundry.com/unifont.html.

**Comment by prepare** [comment]
fixed, in 72f685ed02d3173506e6429d4a8c9bd32c69561b
