### ISSUE TITLE
TextBoxSample.WinForms: rendered text is covered

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#46]
In the demo **TextBoxSample.WinForms**, the rendered text seems to be covered by something white.

![Imgur](http://i.imgur.com/MqOan7e.png)

**Comment by prepare** [comment]
Haha...
I forget to hide the left-upper textbox control and the previous sample render output.

The 'something white' is the 'test' textbox control.
Try type on it or click on it(click position=> small green point).

![test](https://cloud.githubusercontent.com/assets/7447159/25850765/af500e28-34ed-11e7-92b4-b2c831a43418.png)
_pic 1: test! on 'demo' textbox, this shows how to measure string and move the caret._

**Comment by prepare** [comment]
![sample_textbox](https://cloud.githubusercontent.com/assets/7447159/24025652/4e62b33c-0aee-11e7-81f0-ab527753f661.png)

_pic 1: (1) show sample textbox, then press key on it, you can use del/backspace/left/right/home/end buttons to navigate on the text. (2) green point => exact mousedown pos (for debugging), caret (3) will move to the most proper glyph index_
