### ISSUE TITLE
GPOS's PairPosFormat2 is not implemented

### ISSUE THREAD

**Issue by hexland** [LayoutFarm/Typography#48]
My artists have given me a new font that kills the importer - it appears to hit an NotImplementedException in GPOS.cs - at line 581.

The font has been authored in FontForge -- I'm not sure what to look for, or ask them to change to prevent the unsupported table format from being included.

Any suggestions?

**Comment by prepare** [comment]
@hexland : 
please send me that font.
I will look for a bug

**Comment by hexland** [comment]
It's most likely a problem at our end... the font was created in Adobe
Illustrator and packaged with FontForge.  It appears to work fine using the
windows font viewer.

**Comment by hexland** [comment]
[shardphenom_black.zip](https://github.com/LayoutFarm/Typography/files/1184589/shardphenom_black.zip)

**Comment by prepare** [comment]
I can't download from the link ...

[shardphenom_black.zip](https://github.com/LayoutFarm/Typography/files/1184589/shardphenom_black.zip)

please send me to my email wintercoredev[at]gmail.com

**Comment by prepare** [comment]
@hexland , some GPOS subtable may not need when you build a single glyph.
but it is needed for some layout. 

at this point if you want to build a single glyph,
you can comment that throw exception  code.

**Comment by hexland** [comment]
Ah, thats good to know... I'm only building a glyph at a time and building a texture atlas with the MSDF bitmap.  I'll try that now, thanks!

**Comment by prepare** [comment]
@hexland,

What is the (human) language do you want to use with that font? (need for script-lang)

**Comment by hexland** [comment]
Right now, we are only using English/Euro characters (32-255)

**Comment by hexland** [comment]
Removing the throw appears to bypass the problem.  That's enough of a fix for me now!

I'm curious to know what feature that FontForge added that causes the library to hit the exception though?

**Comment by prepare** [comment]
GPOS Type2, Format2 => see https://github.com/LayoutFarm/Typography/issues#issuecomment-521508746
