### ISSUE TITLE
How to get a glyph from character directly?

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#49]
For example, for character 'D', the glyph index for **msjh.ttf** and **Helvetica.ttf** are both 39. But for **unifont-9.0.06.ttf**, the glyph index is 71.

The only way to get a `Glyph` I found is `Typeface.GetGlyphByIndex()`. I want to know whether we can get the glyph from the character `D` directly?

**Comment by prepare** [comment]
easy !

please look for  ...
typeface.LookupIndex(char c); 

it is used in many area.

for example
see https://github.com/LayoutFarm/Typography/blob/master/Demo/Windows/PixelFarmSample.WinForms/Form1.cs#L695

**Comment by prepare** [comment]
But please note that 
1 character may need replacement/substitution if  you pass it to advanced openfont layout (eg. GSUB subtable)

**Comment by zwcloud** [comment]
OK, Thank you!
