### ISSUE TITLE
Using Typography in my GUI lib.

### ISSUE THREAD

**Issue by zwcloud** [LayoutFarm/Typography#51]
Hi, @prepare 

I don't know how to get in touch with you so I created this issue. It seems you are not on gitter yet.  Would you mind joining [this gitter group](https://gitter.im/ImGui/ImGui)? We can discuss about further development of Typography together. 

I have published [my GUI lib](https://github.com/zwcloud/ImGui). [A former version of Typography](https://github.com/zwcloud/ImGui/tree/master/src/ImGui/3rd/Typography) is included.

You can see how Typography is used in [`TypographyTextContext`](https://github.com/zwcloud/ImGui/blob/master/src/ImGui/OSImplentation/TypographyTextContext.cs).

Currently the text size and postion got from `TypographyTextContext` is not accurate. I will look into this issue later.

PS: Don't worry about the LGPL license. I'll grant you a permissive license for codes that directly related to Typography.

**Comment by prepare** [comment]
@zwcloud , 

1. Thank you for your invitation. 
    Currently, The best way to contact me is  GitHub issue.

2. Today, I see your [progject](https://zwcloud.net/#project/imgui), 
    I 'm  so HAPPY that this project is useful for others.
   
3. I'm really worry about touching any copy-left code. (GPL, LGPL, Mozilla etc) 
   That's why I can't use Pango Lib.  
  
   Even your code is copy-left + 'special'  permission => I can't use it.
   and  I would like to ask you to change it to a permissive license one).

(  the original dear ImGui use MIT license, 
  why don't you use the same, why do you choose LGPL for your 'Hello ImGui')

**Comment by zwcloud** [comment]
> why do you choose LGPL
I use LGPL because I want other's improvement and modification back. I feel sorry but I won't change it to MIT.

> Even your code is copy-left + 'special' permission => I can't use it.
> and I would like to ask you to change it to a permissive one).
That's OK. I will refactor the code related to Typography to another MIT licensed repo or just create a pull request that merges them to Typography. But I don't have time recently.

For example, [`GlyphLoader` ](https://github.com/zwcloud/ImGui/blob/master/src/ImGui/DrawList/Text/GlyphLoader.cs), [`GlyphCache`](https://github.com/zwcloud/ImGui/blob/master/src/ImGui/DrawList/Text/GlyphCache.cs)
 and [`https://github.com/zwcloud/ImGui/blob/master/src/ImGui/OSImplentation/TypographyTextContext.cs`].

For now you can just take a look at them to get a general idea how Typography is used in another repo. I hope those code can help in further development of Typography.

**Comment by prepare** [comment]
@zwcloud 

Do your best on the  [exam](https://github.com/zwcloud/ImGui),

and get the result as you expect!


Cheer!

**Comment by prepare** [comment]
@zwcloud ,

I add your works on the latest readme page.
