### ISSUE TITLE
Discussing the use of NotImplementedException

### ISSUE THREAD

**Issue by samhocevar** [LayoutFarm/Typography#52]
For the moment, `NotImplementedException` is thrown about whenever an unknown table format is encountered. For instance `GPOS.cs` has 12 such occurrences, `GSUB.cs` has 7, and `GDEF.cs` has 1. But all these three tables are optional in the standard. My understanding is that a client should just ignore the features it does not know about instead of throwing.

How would you feel about replacing those `throw`s with safe fallbacks instead? I can try to do the work but I wanted your thoughts about it first.

(*Context*: I’m currently writing my own parser for a subset of OpenType for [Emoji.Wpf](https://github.com/samhocevar/emoji.wpf) and I thought it might be interesting to use `Typography.OpenFont` instead, and contribute some of my code.)

**Comment by prepare** [comment]
@samhocevar ,

Let do it! :)

( I write the throw exceptions for debug only )

**Comment by samhocevar** [comment]
Great! I started submitting a few changes.

**Comment by prepare** [comment]
Thank you for your Great works!

see https://github.com/LayoutFarm/Typography/commit/f659ef1eadbde3b033ba75c6f6fc3163846a835e

all your PRs have been merged => https://github.com/LayoutFarm/Typography/commits?author=samhocevar
