### ISSUE TITLE
Incorrect RGB ordering

### ISSUE THREAD

**Issue by samhocevar** [LayoutFarm/Typography#62]
If I set `canvasPainter.FillColor = new Color(255, 0, 0);` in `VcxTextPrinter.cs` I would expect that the text is rendered in red, but instead it is rendered in blue (using the PixelFarmSample.WinForms sample).

Swapping `R` and `B` in `ColorOrder.cs` results in the correct color being used, but I don’t know where the actual bug is.

As a result, the code in `CPAL.cs` is incorrect with regards to RGB ordering. The buffer is in `BGRA` format and the `GetColor` code should be as follows:

    b = colorBGRABuffer[startAt];
    g = colorBGRABuffer[startAt + 1];
    r = colorBGRABuffer[startAt + 2];
    a = colorBGRABuffer[startAt + 3];

**Comment by prepare** [comment]
Thank you.

I switch the color order.

see https://github.com/LayoutFarm/Typography/commit/a8341949f32a0c0364bbfb671907c8057ea45cc5
