### ISSUE TITLE
Demo not working for GdiPlus

### ISSUE THREAD

**Issue by acaly** [LayoutFarm/Typography#72]
Hi,

I have an issue on the demo. On my environment the GdiPlus demo is drawing characters at wrong positions. Though not familiar with the library, I tried to dig a little bit, and it seems that the DoGlyphPosition methods do nothing. The positions are not updated at all and remain at (0, 0). 

I am using VS2017 and upgraded solution, but the build is successful (with a lot of warnings). Not sure whether this is the reason.

Thanks in advance.

**Comment by prepare** [comment]
Thank you for your report, 
I will check it again.

**Comment by prepare** [comment]
@acaly 

I fixed it, I forgot to _glyphLayout's font size.

 add 1 line, see =>  https://github.com/LayoutFarm/Typography/commit/d28c240504642057b92fac820a8a1e1f3b0c66fb

---

![issue_72](https://user-images.githubusercontent.com/7447159/32095811-a0352f14-bb2e-11e7-8aea-244e39d742ae.png)

**Comment by prepare** [comment]
Linux, see =>https://github.com/LayoutFarm/Typography/commit/47b68ee8d34f847cecdc6814038312e3b4e5ce7f
