### ISSUE TITLE
CFF

### ISSUE THREAD

**Issue by prepare** [LayoutFarm/Typography#75]
see https://www.microsoft.com/typography/otspec/cff2.htm

http://wwwimages.adobe.com/www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5176.CFF.pdf

**Comment by prepare** [comment]
Temp refs.
 
[5014.CIDFont_Spec.pdf](https://github.com/LayoutFarm/Typography/files/1883574/5014.CIDFont_Spec.pdf)
[5176.cff.pdf](https://github.com/LayoutFarm/Typography/files/1883577/5176.cff.pdf)
[5177.Type2.pdf](https://github.com/LayoutFarm/Typography/files/1883578/5177.Type2.pdf)

**Comment by Happypig375** [comment]
Looking great! I hope that this will continue to be worked on so that I can depend CSharpMath on this.

You have my spiritual support :wink:

**Comment by prepare** [comment]
![latin_0_a](https://user-images.githubusercontent.com/7447159/38690752-1466c73c-3ea9-11e8-841b-54f9c1c3b57f.png)
![latin_4_a](https://user-images.githubusercontent.com/7447159/38690750-139114ac-3ea9-11e8-9302-e3dc52c348ab.png)
![latin_7_a](https://user-images.githubusercontent.com/7447159/38690751-13cea8f8-3ea9-11e8-9610-8e58d23313dc.png)
![latin_1_a](https://user-images.githubusercontent.com/7447159/38690749-1352b52c-3ea9-11e8-9125-78871b787d8f.png)
_pic 4: 0,1,4,7_

**Comment by prepare** [comment]
Hello World!
---
![latin_h](https://user-images.githubusercontent.com/7447159/39096398-b4c64464-4679-11e8-8854-5ff4bf9f62df.png)
![latin_e](https://user-images.githubusercontent.com/7447159/39096397-b48bac3c-4679-11e8-9ddc-a94822d04c0a.png) 
 
![latin_l](https://user-images.githubusercontent.com/7447159/39096421-01ccf60e-467a-11e8-9ac9-6b06922f3975.png)
![latin_l](https://user-images.githubusercontent.com/7447159/39096421-01ccf60e-467a-11e8-9ac9-6b06922f3975.png)
![latin_o](https://user-images.githubusercontent.com/7447159/39096400-b5424438-4679-11e8-9721-bbb31e95766f.png)

--- 

--- 

---

--- 

--- 

--- 

--- 


![latin_w](https://user-images.githubusercontent.com/7447159/39096402-b5c2e354-4679-11e8-892a-e853931a7edd.png)
![latin_o](https://user-images.githubusercontent.com/7447159/39096400-b5424438-4679-11e8-9721-bbb31e95766f.png)
![latin_r](https://user-images.githubusercontent.com/7447159/39096401-b5833dbc-4679-11e8-8902-c673169b2d27.png)
![latin_w](https://user-images.githubusercontent.com/7447159/39096402-b5c2e354-4679-11e8-892a-e853931a7edd.png)
![latin_d](https://user-images.githubusercontent.com/7447159/39096403-b60f4924-4679-11e8-9059-2ed3ac760435.png)
![latin_exclaimation](https://user-images.githubusercontent.com/7447159/39096413-eeb5976a-4679-11e8-8197-055b03afd6a2.png)


---
_pic 5: hello world!, latin-modern-math-regular.otf, cff font_

**Comment by prepare** [comment]
Scale it :)
---
![latin_long](https://user-images.githubusercontent.com/7447159/39185040-f38c8b96-47ef-11e8-878b-3082ab924888.png)


see : https://github.com/LayoutFarm/Typography/commit/e67ae5605d921110c45f680c6097702f0a2db388

**Comment by prepare** [comment]
![latin_long_compare](https://user-images.githubusercontent.com/7447159/39213045-b3b020b4-483a-11e8-9174-9e2a1abda2cf.png)

_pic 7: from pic 6(above), compare with Win7's NotePad, latin-modern-math-regular.otf, 18 pts_

**Comment by prepare** [comment]
Asana Math's Cff font
---

from https://ctan.org/tex-archive/fonts/Asana-Math/


![asana_math1](https://user-images.githubusercontent.com/7447159/39223936-cf98f358-486e-11e8-90bc-c5b5937b5ffe.png)
![asana_math2](https://user-images.githubusercontent.com/7447159/39223939-d31e8ce0-486e-11e8-8817-677db180317a.png)

_pic 10: asana-math-regular,otf_

**Comment by prepare** [comment]
XITS's font
---
otf font (cff1) from https://github.com/khaledhosny/xits



![xits_regular_2](https://user-images.githubusercontent.com/7447159/39224384-50b9df72-4871-11e8-8d9b-73595cfacb7a.png)

_pic 11: XITS otf font_

**Comment by prepare** [comment]
@EliotJones (https://github.com/UglyToad/PdfPig)

Even your goal is to port code from
are porting  the code from PdfBox and FontBox to your PdfPig. 

But  I invite you to visit here.
if you need some info about font manipulation. (both ttf, otf, cff ).

this lib may help your speed too.


:)

**Comment by EliotJones** [comment]
@prepare thank you, I've not had any time to work on PdfPig recently unfortunately due to time constraints but I'll be sure to consult this code when I get back round to it.

Out of interest, since GitHub search is not great, where do you handle parsing of the CharStrings and Private dictionary in CFF files?

**Comment by prepare** [comment]
1. Read CFF structures ( and Handle Dictionaries) => https://github.com/LayoutFarm/Typography/blob/dev/Typography.OpenFont/Tables.CFF/CFF.cs

2. Type2CharString parser => 
https://github.com/LayoutFarm/Typography/blob/dev/Typography.OpenFont/Tables.CFF/Type2CharStringParser.cs

3. Cff Evaluation Engine =>https://github.com/LayoutFarm/Typography/blob/dev/Typography.OpenFont/Tables.CFF/CffEvaluationEngine.cs

**Comment by prepare** [comment]
CFF with CID features=> https://github.com/LayoutFarm/Typography/issues/201
