### ISSUE TITLE
Suggest renaming the .sln file

### ISSUE THREAD

**Issue by samhocevar** [LayoutFarm/Typography#76]
I know it’s not a big deal, but when I <kbd>Alt</kbd>-<kbd>Tab</kbd> through my windows, the VS instance I use for Typography appears as “MainDev”, which is not really descriptive. Any problem with renaming it to `Typography.sln`?

![image](https://user-images.githubusercontent.com/245089/32436285-d588e66c-c2e3-11e7-8da0-1678045fa842.png)

**Comment by prepare** [comment]
OK, 
see 990db56d2d00d453111d3d1f068a6f880283acae
