### ISSUE TITLE
Please clarify a license

### ISSUE THREAD

**Issue by ForNeVeR** [LayoutFarm/Typography#97]
Hello, @prepare. I've decided to contact you in answer to your comment: https://github.com/verybadcat/CSharpMath/issues/1#issuecomment-366409476

Honestly, the license is currently ambiguous. I understand that you've based your code on multiple open-source projects with various licenses, and that's okay. But what exact license does Typography use? Your documentation doesn't provide a definitive answer.

I can see that the licenses are listed in the sources of some (or maybe all?) files of your code. If so, then you should state that more clearly. Maybe something like "This code is based on multiple open-sourced projects (listed below) all using permissive licenses; please, check each source file's header for the licensing info."

Also, that creates some questions regarding the licensing of the resulting artifacts, i.e. what license should you declare if publishing the code into NuGet? Currently the code looks like a mix of BSD, MIT and Apache2 licenses.

- Probably you could state that the license for the whole project is a denominator of these three?
- Or maybe something like _"The user should adhere to the terms of MIT, BSD and Apache2 licenses"_? 
- "MIT\*BSD\*Apache2"?

These three licenses have much in common, and it looks to me _(and I'm not a lawyer)_ like one could follow all of them simultaneously. I hope.

I understand that this is a _nasty_ issue for an engineer-and-not-a-lawyer, but believe me, we __need__ to sort it out.

**Comment by ForNeVeR** [comment]
Another possible idea is to split the project into packages each having its' own license, if that's possible. Then following the terms of a mix of these packages won't be your problem, and that'll be completely up to the user (an that likely won't be an issue for the user for the reasons I've listed above).

**Comment by prepare** [comment]
First thought ...

   This code is based on multiple open-sourced projects (listed below) all using permissive licenses; 

    A license for a whole project is Apache2.  

    but if you use some part of the code
    please check each source file's header for the licensing info.

**Comment by ForNeVeR** [comment]
Is Apache2 compatible with all the others? By following the Apache2 terms, do I automatically follow the terms of MIT and BSD? If so, then everything should be okay I think.

**Comment by prepare** [comment]
please give me a time to check that again :)

ref https://www.quora.com/Is-the-MIT-license-compatible-with-the-Apache-License-Version-2-APLv2

**Comment by prepare** [comment]
from http://apache.org/legal/resolved.html#category-b

>For the purposes of being included in an Apache product, which licenses are considered to be similar in terms to the Apache License 2.0?

    Works under the following licenses may be included within Apache products:

    Apache License 2.0
    Apache Software License 1.1. Including variants:
        PHP License 3.01
        MX4J License
    BSD (without advertising clause). Including variants:
        BSD 2-clause
        BSD 3-clause
        DOM4J License
        PostgreSQL License
        Eclipse Distribution License 1.0
    MIT/X11
    ...
    ...

**Comment by ForNeVeR** [comment]
@prepare 
> from http://apache.org/legal/resolved.html#category-b

It looks like this document talks about the Apache Foundation, not about the Apache license. I.e. it lists the licenses that could be used by projects included in Apache Foundation.

OTOH, http://www.whitesourcesoftware.com/whitesource-blog/top-10-apache-license-questions-answered/ lists some of the differences between BSD/MIT and Apache2. The main one is that by providing Apache2 license, you explicitly give a patent grant to your users. Unfortunately, _it seems to me_ like you can't provide such a grant to users of your library, because you don't own any patents for the code of other libraries used by the project. It means like you can't give your users that right, and so Apache2 license couldn't be applied to the Typography code by you.

[Here](https://www.quora.com/I-have-an-Apache-2-0-Licensed-project-and-I-would-like-to-use-MIT-licensed-components-What-are-my-sublicensing-relicensing-obligations) people say that you could, in fact, relicense the Apache2 code to MIT (but should provide both Apache2 and MIT license texts with your source package). Maybe we should follow that path? What do you think?

**Comment by prepare** [comment]
Second thought ...

The project is based on multiple open-sourced projects (listed below) all using permissive licenses;

A license for a whole project is **MIT**.

but if you use some part of the code
please check each source file's header for the licensing info.

**Comment by ForNeVeR** [comment]
Looks good to me! 👍

**Comment by prepare** [comment]
I've updated the license file. (see https://github.com/LayoutFarm/Typography/blob/master/LICENSE.md)
