### ISSUE TITLE
What are each project used for?

### ISSUE THREAD

**Issue by Happypig375** [LayoutFarm/Typography#99]
It seems like Typography.OpenFont and Typography.GlyphLayout are the most important ones.
While digging through the demos (also note the weird namings of them),
I see that Typography.Contours are also used.
This makes me wonder what each project is supposed to provide.

**Comment by prepare** [comment]
1) Typography.OpenFont 

- This project is a core project, no dependency on others.
- This project contains a font reader that implements OpenFont Format.
  (ISO/IEC 14496-22:2015 , and Microsoft OpenType Specification)

- No sophisticated OpenType layout mechanism here
- No Visual/Graphics Rendering Here
---
2) Typography.GlyphLayout 

_since GlyphLayout engine is not stable and quite complex, 
I separated this from the OpenFont core project_

- This project implement OpenType Layout Engine/Mechanism (esp. GSUB, GPOS).
- The engine converts a string to a glyph-index List and substitutes some glyph,
   and place them  into a proper position  by the request 'settings' 
      eg  see https://github.com/LayoutFarm/Typography/issues/82, 
           or https://github.com/LayoutFarm/Typography/issues/18
- No Visual/Graphics Rendering Here
 ---

With Typography.OpenFont  + Typography.GlyphLayout 

you can use the font data/ text/ glyph position to
render to 'your' render surface. 

I provide the example for this 

eg ...

- Render to classic GDI+ WinForms => https://github.com/LayoutFarm/Typography/tree/master/Demo/Windows/GdiPlusSample.WinForms

- Render to [PixelFarm ](https://github.com/PaintLab/PixelFarm)  => https://github.com/LayoutFarm/Typography/tree/master/Demo/Windows/PixelFarmSample.WinForms   

or other projects that use only 2 libs to renderer to there surfaces. 

see ...

- https://github.com/samhocevar/emoji.wpf

- https://github.com/zwcloud/ImGui

---

**Comment by Happypig375** [comment]
What about Typography.Contours and others?
Typography.Contours targets .NET Framework 2.0 and cannot be referenced from .NET Standard 2.0.

**Comment by prepare** [comment]
But when I want to parse a long text and render like this ...

---
The HtmlRenderer example!
---

This is a snapshot of Html drawboard from (https://github.com/LayoutFarm/HtmlRenderer).
The glyphs are generated/layouted with our _Typography_, and rendered with
the PixelFarm (https://github.com/PaintLab/PixelFarm)

![html_renderer_with_selection2](https://user-images.githubusercontent.com/7447159/34453250-b149ecce-ed81-11e7-885b-e4b02460fcf7.png)
_pic 1: HtmlRenderer on GLES2 surface, text are renderered with the Typography_

---

I need more functions about how to parse a long text
and layout it.

  
So I need more functions, That are in development stage.


3)  Typography.TextServices

     _This is a hub of do some advance things about how to parse a long text and layout them
     The project contains 2 sub-projects( TextBreak and TextFlow)_

4)  Typography.TextBreak   

   - This implements text-break engine.

   - Implements how to break a long text to a list of 'textspan'
     for some languages(eg English) , a text can be parsed into a list of textspan by whitespace break
     but some languages (eg Thai, Laos) can't, They need more advance parsing algorhytm eg=> Dictionary Breaking Engine.
 
5) Typography.TextFlow 
 
   - This implements text flow. How to flow a text into a specific shape area.

---

**Comment by Happypig375** [comment]
This should probably be put in README.

**Comment by prepare** [comment]
6. FontAtlas  [see](https://github.com/LayoutFarm/Typography/tree/master/FontAtlas)

You can see in the pic1 that I render the Html into OpenGLES2 surface.

Rendering a text into GLES2 surface may has multiple ways

One technique is using Font texture atlas.

I provide How to create font Atlas in the project

---

**Comment by prepare** [comment]
7. Msdf Texture see [](url)

   When we talk about FontAtlas. 
   There are many kind of Font Atlas.
   
   If you need scaleable texture font  with 'Sharp' edge=>
   one of them is Multi-channel signed distance field (Msdf) Texture
  
   I also 'port'  Multi-channel signed distance field (Msdf) Texture
   (https://github.com/Chlumsky/msdfgen) from C/C++ to C#

**Comment by prepare** [comment]
8. Typography.Contours
 
-  This is a developing project.
-  I use this for glyph shape analysis/study.
-  I try to implement AutoHint here
 
eg. 

![glyph_analysis_fit_e_21](https://cloud.githubusercontent.com/assets/7447159/25597023/94298aae-2ef6-11e7-9bcc-6103358f6ea9.png)

_pic 1: grid w,h (1px,10px)_

![glyph_analysis_fit_u_21](https://cloud.githubusercontent.com/assets/7447159/25597024/942cf860-2ef6-11e7-87c8-ca86171f6aa9.png)
_pic 2: grid w,h (1px,10px)_

 
(see https://github.com/PaintLab/PixelFarm/issues/4 , https://github.com/LayoutFarm/Typography/issues/37)

**Comment by prepare** [comment]
Under development Tyography.Contours

---

Century font, A, 460pts
---
![glyph_analysis_a_40](https://cloud.githubusercontent.com/assets/7447159/25427957/6b3c9f8e-2a9e-11e7-8ac6-11cac7185745.png)
_pic 1: master outline_

![glyph_analysis_a_46](https://cloud.githubusercontent.com/assets/7447159/25427961/6b54a070-2a9e-11e7-8750-6f89adeb9241.png)

_pic 2: from 1_

![glyph_analysis_a_41](https://cloud.githubusercontent.com/assets/7447159/25427956/6b3ad8de-2a9e-11e7-9a1d-4ac419b2827f.png)
_pic 3: from 1, master outline  with edge offset -10px (thin)_

![glyph_analysis_a_47](https://cloud.githubusercontent.com/assets/7447159/25427958/6b3db82e-2a9e-11e7-95bb-441c761a0ecc.png)
_pic 4: from 3_

![glyph_analysis_a_42](https://cloud.githubusercontent.com/assets/7447159/25427959/6b3dd41c-2a9e-11e7-97ed-8464b915ea06.png)
_pic 5: from 1, master outline  with edge offset +10px (thick)_


![glyph_analysis_a_45](https://cloud.githubusercontent.com/assets/7447159/25427960/6b40be52-2a9e-11e7-9424-22c1c821ec0e.png)

_pic 5: from 4_

**Comment by prepare** [comment]
Naming something sometimes quite hard :)

Welcome all new suggestion about that.

**Comment by Happypig375** [comment]
Can you post this useful information at README?
